=== open-contracting/standard/standard/schema/release-package-schema.json
{
  "id": "http://standard.open-contracting.org/1.1-dev/en/release-package-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema for an Open Contracting Release Package",
  "description": "Note that all releases within a release package must have a unique releaseID within this release package.",
  "type": "object",
  "required": [
    "uri",
    "publisher",
    "publishedDate",
    "releases",
    "version"
  ],
  "properties": {
    "uri": {
      "title": "Package identifier",
      "description": "The URI of this package that identifies it uniquely in the world. Recommended practice is to use a deferenceable URI, where a persistent copy of this package is available.",
      "type": "string",
      "format": "uri"
    },
    "version": {
      "title": "OCDS schema version",
      "description": "The version of the OCDS schema used in this package, expressed as major.minor For example: 1.0 or 1.1",
      "type": "string",
      "pattern": "^(\\d+\\.)(\\d+)$"
    },
    "extensions": {
      "title": "OCDS extensions",
      "description": "An array of OCDS extensions used in this package. Each entry should be a url to the extension.json file for that extension.",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "publishedDate": {
      "title": "Published date",
      "description": "The date that this package was published. If this package is generated 'on demand', this date should reflect the date of the last change to the underlying contents of the package.",
      "type": "string",
      "format": "date-time"
    },
    "releases": {
      "title": "Releases",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "http://standard.open-contracting.org/1.1-dev/en/release-schema.json"
      },
      "uniqueItems": true
    },
    "publisher": {
      "title": "Publisher",
      "description": "Information to uniquely identify the publisher of this package.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the organisation or department responsible for publishing this data.",
          "type": "string"
        },
        "scheme": {
          "title": "Scheme",
          "description": "The scheme that holds the unique identifiers used to identify the item being identified.",
          "type": [
            "string",
            "null"
          ]
        },
        "uid": {
          "title": "uid",
          "description": "The unique ID for this entity under the given ID scheme. Note the use of 'uid' rather than 'id'. See issue #245.",
          "type": [
            "string",
            "null"
          ]
        },
        "uri": {
          "title": "URI",
          "description": "A URI to identify the publisher.",
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      },
      "required": [
        "name"
      ]
    },
    "license": {
      "title": "License",
      "description": "A link to the license that applies to the data in this package. A Public Domain Dedication or [Open Definition Conformant](http://opendefinition.org/licenses/) license is strongly recommended. The canonical URI of the license should be used. Documents linked from this file may be under other license conditions. ",
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "publicationPolicy": {
      "title": "Publication policy",
      "description": "A link to a document describing the publishers [publication policy](http://standard.open-contracting.org/latest/en/implementation/publication_policy/).",
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    }
  }
}

=== open-contracting/standard/standard/docs/en/examples/implementation.json
{
  "uri": "http://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-05-contract.json",
  "publishedDate": "2011-01-10T09:30:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "http://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "extensions": [],
  "releases": [
    {
      "ocid": "ocds-213czf-000-00001",
      "id": "ocds-213czf-000-00001-06-implementation",
      "date": "2011-01-10T09:30:00Z",
      "language": "en",
      "tag": [
        "implementation"
      ],
      "initiationType": "tender",
      "parties": [
        {
          "identifier": {
            "scheme": "GB-LAC",
            "id": "E09000003",
            "legalName": "London Borough of Barnet",
            "uri": "http://www.barnet.gov.uk/"
          },
          "name": "London Borough of Barnet",
          "address": {
            "streetAddress": "4, North London Business Park, Oakleigh Rd S",
            "locality": "London",
            "region": "London",
            "postalCode": "N11 1NP",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Procurement Team",
            "email": "procurement-team@example.com",
            "telephone": "01234 345 346",
            "faxNumber": "01234 345 345",
            "url": "http://example.com/contact/"
          },
          "roles": [
            "buyer"
          ],
          "id": "GB-LAC-E09000003"
        },
        {
          "identifier": {
            "scheme": "GB-COH",
            "id": "1234567844",
            "legalName": "AnyCorp Ltd",
            "uri": "http://www.anycorp.example"
          },
          "additionalIdentifiers": [
            {
              "scheme": "GB-VAT",
              "id": "987654321"
            }
          ],
          "name": "AnyCorp Cycle Provision",
          "address": {
            "streetAddress": "100 Anytown Lane",
            "locality": "Anytown",
            "region": "AnyCounty",
            "postalCode": "AN1 1TN",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Contracts Team",
            "email": "contracts@anycorp.example",
            "telephone": "12345 456 343",
            "faxNumber": "12345 456 343"
          },
          "roles": [
            "supplier"
          ],
          "id": "GB-COH-1234567844"
        }
      ],
      "buyer": {
        "id": "GB-LAC-E09000003",
        "name": "London Borough of Barnet"
      },
      "awards": [
        {
          "id": "ocds-213czf-000-00001-award-01",
          "title": "Award of contract to build new cycle lanes in the centre of town.",
          "description": "AnyCorp Ltd has been awarded the contract to build new cycle lanes in the centre of town.",
          "status": "active",
          "date": "2010-05-10T10:30:00Z",
          "value": {
            "amount": 11000000,
            "currency": "GBP"
          },
          "suppliers": [
            {
              "id": "GB-COH-1234567844",
              "name": "AnyCorp Cycle Provision"
            }
          ],
          "items": [
            {
              "id": "0001",
              "description": "string",
              "classification": {
                "scheme": "CPV",
                "id": "45233130",
                "description": "Construction work for highways",
                "uri": "http://cpv.data.ac.uk/code-45233130"
              },
              "additionalClassifications": [
                {
                  "scheme": "CPV",
                  "id": "45233162-2",
                  "description": "Cycle path construction work",
                  "uri": "http://cpv.data.ac.uk/code-45233162.html"
                }
              ],
              "quantity": 8,
              "unit": {
                "name": "Miles",
                "value": {
                  "amount": 137000,
                  "currency": "GBP"
                }
              }
            }
          ],
          "contractPeriod": {
            "startDate": "2010-07-01T00:00:00Z",
            "endDate": "2011-08-01T23:59:00Z"
          },
          "documents": [
            {
              "id": "0007",
              "documentType": "notice",
              "title": "Award notice",
              "description": "Award of contract to build new cycle lanes in the centre of town to AnyCorp Ltd.",
              "url": "http://example.com/tender-notices/ocds-213czf-000-00001-04.html",
              "datePublished": "2010-05-10T10:30:00Z",
              "format": "text/html",
              "language": "en"
            }
          ]
        }
      ],
      "contracts": [
        {
          "id": "ocds-213czf-000-00001-contract-01",
          "awardID": "ocds-213czf-000-00001-award-01",
          "title": "Contract to build new cycle lanes in the centre of town.",
          "description": "Contract monitoring for cycle lane construction.",
          "status": "active",
          "period": {
            "startDate": "2010-07-01T00:00:00Z",
            "endDate": "2011-08-01T23:59:00Z"
          },
          "value": {
            "amount": 11000000,
            "currency": "GBP"
          },
          "items": [
            {
              "id": "0001",
              "description": "string",
              "classification": {
                "scheme": "CPV",
                "id": "45233130",
                "description": "Construction work for highways",
                "uri": "http://cpv.data.ac.uk/code-45233130"
              },
              "additionalClassifications": [
                {
                  "scheme": "CPV",
                  "id": "45233162-2",
                  "description": "Cycle path construction work",
                  "uri": "http://cpv.data.ac.uk/code-45233162.html"
                }
              ],
              "quantity": 8,
              "unit": {
                "name": "Miles",
                "value": {
                  "amount": 137000,
                  "currency": "GBP"
                }
              }
            }
          ],
          "dateSigned": "2015-06-10T14:23:12Z",
          "documents": [
            {
              "id": "0009",
              "documentType": "physicalProcessReport",
              "title": "Progress report",
              "description": "Physical progress report for cycle path construction",
              "url": "http://example.com/reports/ocds-213czf-000-00001/cycle-path-01.pdf",
              "datePublished": "2010-12-15T15:34:02Z",
              "format": "application/pdf",
              "language": "en"
            }
          ],
          "implementation": {
            "transactions": [
              {
                "id": "ocds-213czf-000-00001-1",
                "source": "https://openspending.org/uk-barnet-spending/",
                "date": "2010-08-01T00:00:00Z",
                "uri": "https://openspending.org/uk-barnet-spending/transaction/asd9235qaghvs1059620ywhgai",
                "payer": {
                  "id": "GB-LAC-E09000003",
                  "name": "London Borough of Barnet"
                },
                "payee": {
                  "id": "GB-COH-1234567844",
                  "name": "AnyCorp Ltd"
                },
                "value": {
                  "amount": 500000,
                  "currency": "GBP"
                }
              },
              {
                "id": "ocds-213czf-000-00001-2",
                "source": "https://openspending.org/uk-barnet-spending/",
                "date": "2010-10-01T00:00:00Z",
                "uri": "https://openspending.org/uk-barnet-spending/transaction/asd9235qaghvs105962as0012",
                "payer": {
                  "id": "GB-LAC-E09000003",
                  "name": "London Borough of Barnet"
                },
                "payee": {
                  "id": "GB-COH-1234567844",
                  "name": "AnyCorp Ltd"
                },
                "value": {
                  "amount": 100000,
                  "currency": "GBP"
                }
              }
            ]
          }
        }
      ]
    }
  ]
}
