=== open-contracting/standard/standard/schema/release-package-schema.json
{
  "id": "http://standard.open-contracting.org/1.1-dev/en/release-package-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema for an Open Contracting Release Package",
  "description": "Note that all releases within a release package must have a unique releaseID within this release package.",
  "type": "object",
  "required": [
    "uri",
    "publisher",
    "publishedDate",
    "releases",
    "version"
  ],
  "properties": {
    "uri": {
      "title": "Package identifier",
      "description": "The URI of this package that identifies it uniquely in the world. Recommended practice is to use a deferenceable URI, where a persistent copy of this package is available.",
      "type": "string",
      "format": "uri"
    },
    "version": {
      "title": "OCDS schema version",
      "description": "The version of the OCDS schema used in this package, expressed as major.minor For example: 1.0 or 1.1",
      "type": "string",
      "pattern": "^(\\d+\\.)(\\d+)$"
    },
    "extensions": {
      "title": "OCDS extensions",
      "description": "An array of OCDS extensions used in this package. Each entry should be a url to the extension.json file for that extension.",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "publishedDate": {
      "title": "Published date",
      "description": "The date that this package was published. If this package is generated 'on demand', this date should reflect the date of the last change to the underlying contents of the package.",
      "type": "string",
      "format": "date-time"
    },
    "releases": {
      "title": "Releases",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "http://standard.open-contracting.org/1.1-dev/en/release-schema.json"
      },
      "uniqueItems": true
    },
    "publisher": {
      "title": "Publisher",
      "description": "Information to uniquely identify the publisher of this package.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the organisation or department responsible for publishing this data.",
          "type": "string"
        },
        "scheme": {
          "title": "Scheme",
          "description": "The scheme that holds the unique identifiers used to identify the item being identified.",
          "type": [
            "string",
            "null"
          ]
        },
        "uid": {
          "title": "uid",
          "description": "The unique ID for this entity under the given ID scheme. Note the use of 'uid' rather than 'id'. See issue #245.",
          "type": [
            "string",
            "null"
          ]
        },
        "uri": {
          "title": "URI",
          "description": "A URI to identify the publisher.",
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      },
      "required": [
        "name"
      ]
    },
    "license": {
      "title": "License",
      "description": "A link to the license that applies to the data in this package. A Public Domain Dedication or [Open Definition Conformant](http://opendefinition.org/licenses/) license is strongly recommended. The canonical URI of the license should be used. Documents linked from this file may be under other license conditions. ",
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "publicationPolicy": {
      "title": "Publication policy",
      "description": "A link to a document describing the publishers [publication policy](http://standard.open-contracting.org/latest/en/implementation/publication_policy/).",
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    }
  }
}

=== open-contracting/standard/standard/docs/en/examples/merging/merge-tender-1.json
{
  "uri": "http://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-02-tender.json",
  "publishedDate": "2016-01-01T09:30:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "http://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "extensions": [],
  "releases": [
    {
      "ocid": "ocds-213czf-000-00002",
      "id": "ocds-213czf-000-00002-01-tender",
      "date": "2016-01-01T09:30:00Z",
      "language": "en",
      "tag": [
        "tender"
      ],
      "initiationType": "tender",
      "parties": [
        {
          "name": "Open Data Services",
          "identifier": {
            "scheme": "GB-COH",
            "id": "09506232",
            "legalName": "Open Data Services Co-operative",
            "uri": "https://opencorporates.com/companies/gb/09506232"
          },
          "roles": [
            "buyer"
          ],
          "id": "GB-COH-09506232"
        }
      ],
      "buyer": {
        "id": "GB-COH-09506232",
        "name": "Open Data Services"
      },
      "tender": {
        "id": "ocds-213czf-000-00001-01-tender",
        "title": "Data merging tool",
        "description": "Creation of a data merging tool.",
        "status": "active",
        "value": {
          "amount": 1000,
          "currency": "USD"
        },
        "procurementMethod": "open",
        "awardCriteria": "bestProposal",
        "submissionMethod": [
          "electronicSubmission"
        ],
        "tenderPeriod": {
          "startDate": "2016-01-31T09:00:00Z",
          "endDate": "2016-02-15T18:00:00Z"
        },
        "awardPeriod": {
          "startDate": "2016-04-01T00:00:00Z",
          "endDate": "2016-06-01T23:59:59Z"
        }
      }
    }
  ]
}

=== open-contracting/standard/standard/docs/en/examples/merging/merge-award-1.json
{
  "uri": "http://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-02-tender.json",
  "publishedDate": "2016-03-01T09:30:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "http://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "extensions": [],
  "releases": [
    {
      "ocid": "ocds-213czf-000-00002",
      "id": "ocds-213czf-000-00002-01-award1",
      "date": "2016-03-01T09:30:00Z",
      "language": "en",
      "tag": [
        "award"
      ],
      "initiationType": "tender",
      "parties": [
        {
          "name": "Open Data Services",
          "identifier": {
            "scheme": "GB-COH",
            "id": "09506232",
            "legalName": "Open Data Services Co-operative",
            "uri": "https://opencorporates.com/companies/gb/09506232"
          },
          "roles": [
            "buyer"
          ],
          "id": "GB-COH-09506232"
        }
      ],
      "buyer": {
        "id": "GB-COH-09506232",
        "name": "Open Data Services"
      },
      "award": [
        {
          "id": "ocds-213czf-000-00002-award-supplier-one",
          "title": "Award of contract to create the data merging tool.",
          "description": "Supplier 1 has been commissioned to create the merge tool. A separate contract will be awarded to write the documentation",
          "status": "active",
          "date": "2016-03-01T09:30:00Z",
          "value": {
            "amount": 750,
            "currency": "USD"
          }
        }
      ]
    }
  ]
}

=== open-contracting/standard/standard/docs/en/examples/award.json
{
  "uri": "http://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-04-award.json",
  "publishedDate": "2010-05-10T09:30:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "http://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "extensions": [],
  "releases": [
    {
      "ocid": "ocds-213czf-000-00001",
      "id": "ocds-213czf-000-00001-04-award",
      "date": "2010-05-10T09:30:00Z",
      "language": "en",
      "tag": [
        "award"
      ],
      "initiationType": "tender",
      "parties": [
        {
          "identifier": {
            "scheme": "GB-LAC",
            "id": "E09000003",
            "legalName": "London Borough of Barnet",
            "uri": "http://www.barnet.gov.uk/"
          },
          "name": "London Borough of Barnet",
          "address": {
            "streetAddress": "4, North London Business Park, Oakleigh Rd S",
            "locality": "London",
            "region": "London",
            "postalCode": "N11 1NP",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Procurement Team",
            "email": "procurement-team@example.com",
            "telephone": "01234 345 346",
            "faxNumber": "01234 345 345",
            "url": "http://example.com/contact/"
          },
          "roles": [
            "buyer"
          ],
          "id": "GB-LAC-E09000003"
        },
        {
          "identifier": {
            "scheme": "GB-COH",
            "id": "1234567844",
            "legalName": "AnyCorp Ltd",
            "uri": "http://www.anycorp.example"
          },
          "additionalIdentifiers": [
            {
              "scheme": "GB-VAT",
              "id": "987654321"
            }
          ],
          "name": "AnyCorp Cycle Provision",
          "address": {
            "streetAddress": "100 Anytown Lane",
            "locality": "Anytown",
            "region": "AnyCounty",
            "postalCode": "AN1 1TN",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Contracts Team",
            "email": "contracts@anycorp.example",
            "telephone": "12345 456 343",
            "faxNumber": "12345 456 343"
          },
          "roles": [
            "supplier"
          ],
          "id": "GB-COH-1234567844"
        }
      ],
      "buyer": {
        "id": "GB-LAC-E09000003",
        "name": "London Borough of Barnet"
      },
      "awards": [
        {
          "id": "ocds-213czf-000-00001-award-01",
          "title": "Award of contract to build new cycle lanes in the centre of town.",
          "description": "AnyCorp Ltd has been awarded the contract to build new cycle lanes in the centre of town.",
          "status": "pending",
          "date": "2010-05-10T09:30:00Z",
          "value": {
            "amount": 11000000,
            "currency": "GBP"
          },
          "suppliers": [
            {
              "id": "GB-COH-1234567844",
              "name": "AnyCorp Cycle Provision"
            }
          ],
          "items": [
            {
              "id": "0001",
              "description": "string",
              "classification": {
                "scheme": "CPV",
                "id": "45233130",
                "description": "Construction work for highways",
                "uri": "http://cpv.data.ac.uk/code-45233130"
              },
              "additionalClassifications": [
                {
                  "scheme": "CPV",
                  "id": "45233162-2",
                  "description": "Cycle path construction work",
                  "uri": "http://cpv.data.ac.uk/code-45233162.html"
                }
              ],
              "quantity": 8,
              "unit": {
                "name": "Miles",
                "value": {
                  "amount": 137000,
                  "currency": "GBP"
                }
              }
            }
          ],
          "contractPeriod": {
            "startDate": "2010-07-01T00:00:00Z",
            "endDate": "2011-08-01T23:59:00Z"
          },
          "documents": [
            {
              "id": "0007",
              "documentType": "notice",
              "title": "Award notice",
              "description": "Award of contract to build new cycle lanes in the centre of town to AnyCorp Ltd.",
              "url": "http://example.com/tender-notices/ocds-213czf-000-00001-04.html",
              "datePublished": "2010-05-10T09:30:00Z",
              "format": "text/html",
              "language": "en"
            }
          ]
        }
      ]
    }
  ]
}

=== open-contracting/standard/standard/docs/en/examples/merging/merge-tender-3.json
{
  "uri": "http://standard.open-contracting.org/examples/releases/ocds-213czf-000-00002-01-tender-amendment.json",
  "publishedDate": "2016-02-05T10:30:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "http://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "extensions": [],
  "releases": [
    {
      "ocid": "ocds-213czf-000-00002",
      "id": "ocds-213czf-000-00002-01-tender-amendment",
      "date": "2016-02-05T10:30:00Z",
      "language": "en",
      "tag": [
        "tenderAmendment"
      ],
      "initiationType": "tender",
      "parties": [
        {
          "name": "Open Data Services",
          "identifier": {
            "scheme": "GB-COH",
            "id": "09506232",
            "legalName": "Open Data Services Co-operative",
            "uri": "https://opencorporates.com/companies/gb/09506232"
          },
          "roles": [
            "buyer"
          ],
          "id": "GB-COH-09506232"
        }
      ],
      "buyer": {
        "id": "GB-COH-09506232",
        "name": "Open Data Services"
      },
      "tender": {
        "id": "ocds-213czf-000-00002-01-tender",
        "title": "Data merging tool",
        "description": "Creation of a data merging tool. The tool should by written in Python. Proposals should be submitted by e-mail.",
        "status": "active",
        "value": {
          "amount": 2000,
          "currency": "USD"
        },
        "procurementMethod": "open",
        "awardCriteria": "bestProposal",
        "submissionMethod": [
          "electronicSubmission"
        ],
        "tenderPeriod": {
          "startDate": "2016-01-31T09:00:00Z",
          "endDate": "2016-02-20T18:00:00Z"
        },
        "awardPeriod": {
          "startDate": "2016-04-01T00:00:00Z",
          "endDate": "2016-06-01T23:59:59Z"
        },
        "amendments": [
          {
            "id": "amendment-1",
            "date": "2016-02-04T09:30:00Z",
            "rationale": "Based on feedback from potential bidders, the total budget was increased by Â£500, and the deadline extended",
            "amendsReleaseID": "ocds-213czf-000-00002-01-tender",
            "releaseID": "ocds-213czf-000-00002-01-tender-amendment"
          }
        ]
      }
    }
  ]
}

=== open-contracting/standard/standard/docs/en/examples/tender.json
{
  "uri": "http://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-02-tender.json",
  "publishedDate": "2010-03-01T09:30:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "http://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "extensions": [],
  "releases": [
    {
      "ocid": "ocds-213czf-000-00001",
      "id": "ocds-213czf-000-00001-02-tender",
      "date": "2010-03-15T09:30:00Z",
      "language": "en",
      "tag": [
        "tender"
      ],
      "initiationType": "tender",
      "parties": [
        {
          "identifier": {
            "scheme": "GB-LAC",
            "id": "E09000003",
            "legalName": "London Borough of Barnet",
            "uri": "http://www.barnet.gov.uk/"
          },
          "name": "London Borough of Barnet",
          "address": {
            "streetAddress": "4, North London Business Park, Oakleigh Rd S",
            "locality": "London",
            "region": "London",
            "postalCode": "N11 1NP",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Procurement Team",
            "email": "procurement-team@example.com",
            "telephone": "01234 345 346",
            "faxNumber": "01234 345 345",
            "url": "http://example.com/contact/"
          },
          "roles": [
            "procuringEntity",
            "buyer"
          ],
          "id": "GB-LAC-E09000003"
        }
      ],
      "buyer": {
        "id": "GB-LAC-E09000003",
        "name": "London Borough of Barnet"
      },
      "tender": {
        "id": "ocds-213czf-000-00001-01-tender",
        "title": "Planned cycle lane improvements",
        "description": "Tenders solicited for work to build new cycle lanes in the centre of town.",
        "status": "active",
        "items": [
          {
            "id": "0001",
            "description": "string",
            "classification": {
              "scheme": "CPV",
              "id": "45233130",
              "description": "Construction work for highways",
              "uri": "http://cpv.data.ac.uk/code-45233130"
            },
            "additionalClassifications": [
              {
                "scheme": "CPV",
                "id": "45233162-2",
                "description": "Cycle path construction work",
                "uri": "http://cpv.data.ac.uk/code-45233162.html"
              }
            ],
            "quantity": 8,
            "unit": {
              "name": "Miles",
              "value": {
                "amount": 120000,
                "currency": "GBP"
              }
            }
          }
        ],
        "minValue": {
          "amount": 600000,
          "currency": "GBP"
        },
        "value": {
          "amount": 1100000,
          "currency": "GBP"
        },
        "procurementMethod": "open",
        "procurementMethodRationale": "An open competitive tender is required by EU Rules",
        "awardCriteria": "bestProposal",
        "awardCriteriaDetails": "The best proposal, subject to value for money requirements, will be accepted.",
        "submissionMethod": [
          "electronicSubmission"
        ],
        "submissionMethodDetails": "Submit through the online portal at http://example.com/submissions/ocds-213czf-000-00001-01/",
        "enquiryPeriod": {
          "startDate": "2010-03-01T09:00:00Z",
          "endDate": "2010-03-14T17:30:00Z"
        },
        "hasEnquiries": false,
        "tenderPeriod": {
          "startDate": "2010-03-01T09:00:00Z",
          "endDate": "2011-04-01T18:00:00Z"
        },
        "awardPeriod": {
          "startDate": "2010-06-01T00:00:00Z",
          "endDate": "2011-08-01T23:59:59Z"
        },
        "procuringEntity": {
          "id": "GB-LAC-E09000003",
          "name": "London Borough of Barnet"
        },
        "documents": [
          {
            "id": "0005",
            "documentType": "notice",
            "title": "Tender Notice",
            "description": "Official tender notice.",
            "url": "http://example.com/tender-notices/ocds-213czf-000-00001-01.html",
            "datePublished": "2010-03-01T09:00:00Z",
            "format": "text/html",
            "language": "en"
          }
        ]
      }
    }
  ]
}

=== open-contracting/standard/standard/docs/en/examples/planning.json
{
  "uri": "http://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-01-planning.json",
  "publishedDate": "2009-03-15T14:45:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "http://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "extensions": [],
  "releases": [
    {
      "ocid": "ocds-213czf-000-00001",
      "id": "ocds-213czf-000-00001-01-planning",
      "date": "2009-03-15T14:45:00Z",
      "language": "en",
      "tag": [
        "planning"
      ],
      "initiationType": "tender",
      "parties": [
        {
          "identifier": {
            "scheme": "GB-LAC",
            "id": "E09000003",
            "legalName": "London Borough of Barnet",
            "uri": "http://www.barnet.gov.uk/"
          },
          "name": "London Borough of Barnet",
          "address": {
            "streetAddress": "4, North London Business Park, Oakleigh Rd S",
            "locality": "London",
            "region": "London",
            "postalCode": "N11 1NP",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Procurement Team",
            "email": "procurement-team@example.com",
            "telephone": "01234 345 346",
            "faxNumber": "01234 345 345",
            "url": "http://example.com/contact/"
          },
          "roles": [
            "procuringEntity",
            "buyer"
          ],
          "id": "GB-LAC-E09000003"
        }
      ],
      "buyer": {
        "id": "GB-LAC-E09000003",
        "name": "London Borough of Barnet"
      },
      "planning": {
        "budget": {
          "source": "https://openspending.org/uk-barnet-budget/entries/6801ad388f3a38b7740dde20108c58b35984ee91",
          "id": "6801ad388f3a38b7740dde20108c58b35984ee91",
          "description": "Budget allocation for highway maintenance, aligned with 2015 strategic plan. ",
          "amount": {
            "amount": 6700000.0,
            "currency": "GBP"
          },
          "project": "Central Junction Cycle Scheme",
          "projectID": "SP001",
          "uri": "https://openspending.org/uk-barnet-budget/entries/6801ad388f3a38b7740dde20108c58b35984ee91"
        },
        "rationale": "The 2009 Strategic Plan identifies a need for an improved cycle route in the centre of town.",
        "documents": [
          {
            "id": "0001",
            "documentType": "procurementPlan",
            "title": "Area Wide Cycle Improvements - Procurement Plan",
            "description": "The overall strategic framework for procurement to enhance cycle provision.",
            "url": "http://example.com/opencontracting/documents/planning/highways/procurementPlan.pdf",
            "datePublished": "2009-01-05T00:00:00Z",
            "format": "application/pdf",
            "language": "en"
          },
          {
            "id": "0002",
            "documentType": "needsAssessment",
            "title": "Cycle provision - Needs Assessment",
            "description": "Needs assessment for provision for cyclists in the centre of town.",
            "url": "http://example.com/opencontracting/documents/ocds-213czf-000-00001/needsAssessment.pdf",
            "datePublished": "2009-01-15T00:00:00Z",
            "format": "application/pdf",
            "language": "en"
          }
        ]
      },
      "tender": {
        "id": "ocds-213czf-000-00001-01-planning",
        "title": "Planned cycle lane improvements",
        "description": "The authority plans to tender for improvements to the cycle lane in early 2010. This notice provides advanced notice of the intention to tender, and details to upcoming consultation events.",
        "status": "planned",
        "items": [
          {
            "id": "0001",
            "description": "string",
            "classification": {
              "scheme": "CPV",
              "id": "45233130",
              "description": "Construction work for highways",
              "uri": "http://cpv.data.ac.uk/code-45233130"
            },
            "additionalClassifications": [
              {
                "scheme": "CPV",
                "id": "45233162-2",
                "description": "Cycle path construction work",
                "uri": "http://cpv.data.ac.uk/code-45233162.html"
              }
            ],
            "quantity": 10,
            "unit": {
              "name": "Miles",
              "value": {
                "amount": 100000,
                "currency": "GBP"
              }
            }
          }
        ],
        "minValue": {
          "amount": 500000,
          "currency": "GBP"
        },
        "value": {
          "amount": 1000000,
          "currency": "GBP"
        },
        "procurementMethod": "open",
        "procurementMethodRationale": "An open competitive tender is required by EU Rules",
        "awardCriteria": "bestProposal",
        "awardCriteriaDetails": "The best proposal, subject to value for money requirements, will be accepted.",
        "tenderPeriod": {
          "startDate": "2010-02-01T00:00:00Z"
        },
        "awardPeriod": {
          "startDate": "2010-06-01T00:00:00Z",
          "endDate": "2011-06-01T23:59:59Z"
        },
        "procuringEntity": {
          "id": "GB-LAC-E09000003",
          "name": "London Borough of Barnet"
        },
        "documents": [
          {
            "id": "0003",
            "documentType": "x_consultationDocument",
            "title": "Consultation on cycle provision",
            "description": "A consultation document inviting citizen input into cycle provision.",
            "url": "http://example.com/consultations/cycle-provision/",
            "datePublished": "2015-02-15T00:00:00Z",
            "dateModified": "2015-02-15T00:00:00Z",
            "format": "text/html",
            "language": "en"
          },
          {
            "id": "0004",
            "documentType": "x_map",
            "title": "Map of affected areas",
            "description": "A map showing areas affected by the planned highway updates. Available from local libraries.",
            "datePublished": "2015-02-15T00:00:00Z",
            "format": "offline/print",
            "language": "en"
          }
        ],
        "milestones": [
          {
            "id": "0001",
            "title": "Consultation Period",
            "description": "A consultation period is open for citizen input to shape the final plans.",
            "dueDate": "2015-04-15T17:00:00Z"
          }
        ]
      }
    }
  ]
}
