=== open-contracting/standard/schema/record-package-schema.json
{
  "id": "https://standard.open-contracting.org/schema/1__1__5/record-package-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema for an Open Contracting Record package",
  "description": "The record package contains a list of records along with some publishing metadata.",
  "type": "object",
  "properties": {
    "uri": {
      "title": "Package identifier",
      "description": "The URI of this package that identifies it uniquely in the world.",
      "type": "string",
      "format": "uri",
      "deprecated": {
        "description": "This field mirrored the `uri` field in the release package schema, which is deprecated.",
        "deprecatedVersion": "1.2"
      }
    },
    "version": {
      "title": "OCDS schema version",
      "description": "The version of the OCDS schema used in this package, expressed as major.minor For example: 1.0 or 1.1",
      "type": "string",
      "pattern": "^(\\d+\\.)(\\d+)$"
    },
    "extensions": {
      "title": "OCDS extensions",
      "description": "An array of OCDS extensions used in this package, in which each array item is the URL of an extension.json file.",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "publisher": {
      "title": "Publisher",
      "description": "Information to uniquely identify the publisher of this package.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the organization or department responsible for publishing this OCDS data.",
          "type": "string"
        },
        "scheme": {
          "title": "Scheme",
          "description": "The scheme that holds the unique identifiers used to identify the item being identified.",
          "type": [
            "string",
            "null"
          ]
        },
        "uid": {
          "title": "uid",
          "description": "The unique ID for this entity under the given ID scheme.",
          "type": [
            "string",
            "null"
          ]
        },
        "uri": {
          "title": "URI",
          "description": "A URI to identify the publisher.",
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      },
      "deprecated": {
        "description": "This field is deprecated in favor of the `publisher` field in the release schema.",
        "deprecatedVersion": "1.2"
      }
    },
    "license": {
      "title": "License",
      "description": "A link to the license that applies to the data in this package. A Public Domain Dedication or [Open Definition Conformant](https://opendefinition.org/licenses/) license is recommended. The canonical URI of the license should be used. Documents linked from this file may be under other license conditions.",
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": {
        "description": "It is not critical to distribute the license URL as data. The page linking to the data can express the license.",
        "deprecatedVersion": "1.2"
      }
    },
    "publicationPolicy": {
      "title": "Publication policy",
      "description": "A link to a document describing the publishers publication policy.",
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": {
        "description": "It is not critical to distribute the publication policy URL as data. The page linking to the data can express the publication policy.",
        "deprecatedVersion": "1.2"
      }
    },
    "publishedDate": {
      "title": "Published date",
      "description": "The date that this package was published. If this package is generated 'on demand', this date should reflect the date of the last change to the underlying contents of the package.",
      "type": "string",
      "format": "date-time",
      "deprecated": {
        "description": "This field repeats the maximum `date` among the releases it contains.",
        "deprecatedVersion": "1.2"
      }
    },
    "packages": {
      "title": "Packages",
      "description": "A list of URIs of all the release packages that were used to create this record package.",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "format": "uri"
      },
      "uniqueItems": true,
      "deprecated": {
        "description": "This field is deprecated, because it is rarely implemented, is rarely used, and depends on a publication pattern in which release packages are published at stable URLs.",
        "deprecatedVersion": "1.2"
      }
    },
    "records": {
      "title": "Records",
      "description": "The records for this data package.",
      "type": "array",
      "items": {
        "$ref": "https://standard.open-contracting.org/schema/1__2__0/record-schema.json"
      }
    }
  },
  "required": [
    "records",
    "version"
  ]
}

=== open-contracting/standard/docs/examples/no_change_history/compiled_release.json
{
  "uri": "https://api.quienesquien.wiki/v3/record?ocid=ocds-rwubve-2020CD-000051-0021400002",
  "version": "1.1",
  "publisher": {
    "name": "QuienEsQuien.wiki",
    "uri": "https://quienesquien.wiki/"
  },
  "license": "https://creativecommons.org/licenses/by-sa/4.0/deed.es",
  "publicationPolicy": "https://quienesquien.wiki/about",
  "publishedDate": "2021-11-28T01:53:02.000Z",
  "records": [
    {
      "ocid": "ocds-rwubve-2020CD-000051-0021400002",
      "compiledRelease": {
        "ocid": "ocds-rwubve-2020CD-000051-0021400002",
        "id": "2020CD-000051-0021400002",
        "initiationType": "tender",
        "tag": [
          "compiled"
        ],
        "language": "es",
        "parties": [
          {
            "id": "instituto-costarricense-de-acueductos-y-alcantarillados",
            "name": "Instituto Costarricense de Acueductos y Alcantarillados",
            "roles": [
              "buyer"
            ],
            "address": {
              "countryName": "Costa Rica"
            }
          },
          {
            "name": "DEPOSITO DE MADERAS Y MATERIALES EL TRINITEÑO SOCIEDAD ANONIMA",
            "id": "deposito-de-maderas-y-materiales-el-triniteno-sociedad-anonima",
            "roles": [
              "supplier"
            ],
            "identifier": {
              "id": "3101161310",
              "scheme": "Registro Nacional"
            },
            "address": {
              "countryName": "Costa Rica",
              "streetAddress": "200 mtrs norte de la plaza de deportes Trinidad",
              "locality": "Moravia",
              "region": "San José"
            }
          }
        ],
        "buyer": {
          "name": "Instituto Costarricense de Acueductos y Alcantarillados",
          "id": "instituto-costarricense-de-acueductos-y-alcantarillados"
        },
        "tender": {
          "id": "2020CD-000051-0021400002",
          "status": "complete",
          "procuringEntity": {
            "id": "instituto-costarricense-de-acueductos-y-alcantarillados",
            "name": "Instituto Costarricense de Acueductos y Alcantarillados"
          },
          "value": {
            "amount": 152663,
            "currency": "CRC"
          },
          "procurementMethod": "limited",
          "procurementMethodDetails": "CONTRATACIÓN DIRECTA",
          "procurementMethodRationale": "Cantidad definida",
          "mainProcurementCategory": "goods"
        },
        "awards": [
          {
            "suppliers": [
              {
                "name": "DEPOSITO DE MADERAS Y MATERIALES EL TRINITEÑO SOCIEDAD ANONIMA",
                "id": "deposito-de-maderas-y-materiales-el-triniteno-sociedad-anonima"
              }
            ],
            "status": "active",
            "id": "432020006700078",
            "value": {
              "amount": 704483.81,
              "currency": "CRC"
            },
            "documents": [
              {
                "id": "doc-tdc-432020006700078-1",
                "documentType": "awardNotice",
                "url": "https://www.sicop.go.cr/moduloPcont/pcont/ctract/es/CE_CEJ_ESQ001.jsp?sch_instNo=2020CD-000051-0021400002",
                "format": "text/html",
                "language": "es"
              }
            ]
          }
        ],
        "contracts": [
          {
            "title": "21400002 Compra de herramientas menores para las cantonales de la Región Huetar Caribe",
            "id": "432020006700078",
            "awardID": "432020006700078",
            "value": {
              "amount": 704483.81,
              "currency": "CRC"
            },
            "period": {
              "startDate": "2020-12-23T16:13:09.000Z"
            },
            "status": "terminated"
          }
        ],
        "date": "2021-11-28T01:53:02.000Z"
      }
    }
  ]
}
