=== open-contracting/standard/schema/release-package-schema.json
{
  "id": "https://standard.open-contracting.org/schema/1__1__5/release-package-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema for an Open Contracting Release Package",
  "description": "The release package contains a list of releases along with some publishing metadata.",
  "type": "object",
  "required": [
    "releases",
    "version"
  ],
  "properties": {
    "uri": {
      "title": "Package identifier",
      "description": "The URI of this package that identifies it uniquely in the world. Recommended practice is to use a dereferenceable URI, where a persistent copy of this package is available.",
      "type": "string",
      "format": "uri",
      "deprecated": {
        "description": "This field was used by the `packages` field in the record package schema, which is deprecated.",
        "deprecatedVersion": "1.2"
      }
    },
    "version": {
      "title": "OCDS schema version",
      "description": "The version of the OCDS schema used in this package, expressed as major.minor For example: 1.0 or 1.1",
      "type": "string",
      "pattern": "^(\\d+\\.)(\\d+)$"
    },
    "extensions": {
      "title": "OCDS extensions",
      "description": "An array of OCDS extensions used in this package, in which each array item is the URL of an extension.json file.",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "publishedDate": {
      "title": "Published date",
      "description": "The date that this package was published. If this package is generated 'on demand', this date should reflect the date of the last change to the underlying contents of the package.",
      "type": "string",
      "format": "date-time",
      "deprecated": {
        "description": "This field repeats the maximum `date` among the releases it contains.",
        "deprecatedVersion": "1.2"
      }
    },
    "releases": {
      "title": "Releases",
      "description": "An array of one or more OCDS releases.",
      "type": "array",
      "items": {
        "$ref": "https://standard.open-contracting.org/schema/1__1__5/release-schema.json"
      }
    },
    "publisher": {
      "title": "Publisher",
      "description": "Information to uniquely identify the publisher of this package.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the organization or department responsible for publishing this OCDS data.",
          "type": "string"
        },
        "scheme": {
          "title": "Scheme",
          "description": "The scheme that holds the unique identifiers used to identify the item being identified.",
          "type": [
            "string",
            "null"
          ]
        },
        "uid": {
          "title": "uid",
          "description": "The unique ID for this entity under the given ID scheme.",
          "type": [
            "string",
            "null"
          ]
        },
        "uri": {
          "title": "URI",
          "description": "A URI to identify the publisher.",
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      },
      "deprecated": {
        "description": "This field is deprecated in favor of the `publisher` field in the release schema.",
        "deprecatedVersion": "1.2"
      }
    },
    "license": {
      "title": "License",
      "description": "A link to the license that applies to the data in this package. A Public Domain Dedication or [Open Definition Conformant](https://opendefinition.org/licenses/) license is recommended. The canonical URI of the license should be used. Documents linked from this file may be under other license conditions.",
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": {
        "description": "It is not critical to distribute the license URL as data. The page linking to the data can express the license.",
        "deprecatedVersion": "1.2"
      }
    },
    "publicationPolicy": {
      "title": "Publication policy",
      "description": "A link to a document describing the publishers [publication policy](https://standard.open-contracting.org/{{version}}/{{lang}}/guidance/publish/#finalize-your-publication-policy).",
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": {
        "description": "It is not critical to distribute the publication policy URL as data. The page linking to the data can express the publication policy.",
        "deprecatedVersion": "1.2"
      }
    }
  }
}

=== open-contracting/standard/docs/examples/people-in-organizations/guatemala.json
{
  "publishedDate": "2020-04-13T10:30:00-06:00",
  "publisher": {
    "name": "Ministerio de Finanzas"
  },
  "uri": "https://standard.open-contracting.org/examples/ocds-xqjsxa-11922052/NOG-11922052-2",
  "version": "1.1",
  "license": "https://creativecommons.org/publicdomain/",
  "publicationPolicy": "http://bit.ly/OCDS11-publication-policy",
  "releases": [
    {
      "ocid": "ocds-xqjsxa-11922052",
      "id": "NOG-11922052/2",
      "date": "2020-04-13T10:30:00-06:00",
      "tag": [
        "tenderUpdate",
        "award"
      ],
      "initiationType": "tender",
      "parties": [
        {
          "name": "INSTITUTO NACIONAL DE CIENCIAS FORENSES DE GUATEMALA",
          "id": "GT-NIT-53727983",
          "identifier": {
            "scheme": "GT-NIT",
            "id": "53727983"
          },
          "address": {
            "streetAddress": "14 calle 5-49 zona 1",
            "locality": "Guatemala",
            "region": "Guatemala",
            "countryName": "Guatemala"
          },
          "contactPoint": {
            "email": "adquisicionescd@inacif.gob.gt",
            "telephone": "23273100",
            "faxNumber": "22305602",
            "url": "http://www.inacif.gob.gt"
          },
          "roles": [
            "buyer",
            "procuringEntity"
          ],
          "details": {
            "awardCommitteeMembers": [
              {
                "id": "GT-NIT-20520123",
                "name": "VAIL,VASQUEZ,,URI,MIZRAIM",
                "identifier": {
                  "scheme": "GT-NIT",
                  "id": "20520123"
                },
                "membershipType": "full"
              },
              {
                "id": "GT-NIT-11984309",
                "name": "AGUILAR,CARRERA,,SKARLET,SUZETTE",
                "identifier": {
                  "scheme": "GT-NIT",
                  "id": "11984309"
                },
                "membershipType": "full"
              },
              {
                "id": "GT-NIT-72945028",
                "name": "PINEDA,RUIZ,,JENNIFER,PAMELA",
                "identifier": {
                  "scheme": "GT-NIT",
                  "id": "72945028"
                },
                "membershipType": "full"
              },
              {
                "id": "GT-NIT-69974365",
                "name": "CALDERON,MARROQUIN,,WILLIAN,ESTUARDO",
                "identifier": {
                  "scheme": "GT-NIT",
                  "id": "69974365"
                },
                "membershipType": "alternate"
              },
              {
                "id": "GT-NIT-17589371",
                "name": "ESTRADA,CONTRERAS,HERRARTE,JULIA,MICHELLE",
                "identifier": {
                  "scheme": "GT-NIT",
                  "id": "17589371"
                },
                "membershipType": "alternate"
              }
            ]
          }
        },
        {
          "id": "GT-NIT-85946850",
          "name": "INBOX TECHNOLOGY GUATEMALA, SOCIEDAD ANONIMA",
          "identifier": {
            "scheme": "GT-NIT",
            "id": "85946850"
          },
          "address": {
            "streetAddress": "5ta Ave. 5-55 Zona 14 TOrre 1, Nivel II Europlaza World Business Center",
            "locality": "Guatemala",
            "region": "Guatemala",
            "countryName": "Guatemala"
          },
          "contactPoint": {
            "email": "inboxsa@inboxsa.com",
            "telephone": "23869908",
            "faxNumber": "23868800",
            "url": "http://www.inboxsa.com"
          },
          "roles": [
            "tenderer"
          ]
        },
        {
          "id": "GT-NIT-953040",
          "name": "MERCK, SOCIEDAD ANONIMA",
          "identifier": {
            "scheme": "GT-NIT",
            "id": "953040"
          },
          "address": {
            "streetAddress": "12 AVENIDA 0-33 Z.2",
            "locality": "Mixco",
            "region": "Guatemala",
            "countryName": "Guatemala"
          },
          "contactPoint": {
            "telephone": "24102400",
            "faxNumber": "22505485"
          },
          "roles": [
            "tenderer"
          ]
        },
        {
          "id": "GT-NIT-93269846",
          "name": "EQUIPOS Y PRODUCTOS DE LABORATORIO, SOCIEDAD ANONIMA",
          "identifier": {
            "scheme": "GT-NIT",
            "id": "93269846"
          },
          "address": {
            "streetAddress": "2a. calle 2-65 zona 1",
            "locality": "Guatemala",
            "region": "Guatemala",
            "countryName": "Guatemala"
          },
          "contactPoint": {
            "email": "administracion@eprolabsa.com",
            "telephone": "22303489",
            "url": "http://www.eprolabsa.com"
          },
          "roles": [
            "supplier",
            "tenderer"
          ]
        }
      ],
      "buyer": {
        "name": "INSTITUTO NACIONAL DE CIENCIAS FORENSES DE GUATEMALA",
        "id": "GT-NIT-53727983"
      },
      "tender": {
        "id": "NOG-11922052",
        "title": "INSUMOS PARA CROMATOGRAFÍA DE GASES Y LÍQUIDA PARA LOS LABORATORIOS DE CRIMINALÍSTICA DEL INSTITUTO NACIONAL DE CIENCIAS FORENSES DE GUATEMALA",
        "status": "complete",
        "procuringEntity": {
          "name": "INSTITUTO NACIONAL DE CIENCIAS FORENSES DE GUATEMALA",
          "id": "GT-NIT-53727983"
        },
        "items": [
          {
            "id": "1",
            "description": "Aceite para bomba auxiliar de vacío, compatible con el espectrómetro de masas 5973 y 5975C. Presentación frasco de 1 litro",
            "classification": {
              "scheme": "UNSPSC",
              "id": "15121521"
            },
            "quantity": 8
          },
          {
            "id": "2",
            "description": "Arandela con septa de PTFE/Silicona, de 20 mm de diámetro. Presentación paquetes de 100 unidades",
            "classification": {
              "scheme": "UNSPSC",
              "id": "41115717"
            },
            "quantity": 465
          },
          {
            "id": "3",
            "description": "Arandela con septa PTFE de 11mm de diámetro. Presentación paquetes de 1,000 unidades",
            "classification": {
              "scheme": "UNSPSC",
              "id": "41115717"
            },
            "quantity": 30
          }
        ],
        "procurementMethod": "open",
        "procurementMethodDetails": "Licitación Pública (Art. 17 LCE)",
        "mainProcurementCategory": "goods",
        "submissionMethod": [
          "electronicSubmission"
        ],
        "tenderPeriod": {
          "startDate": "2020-02-14T15:40:32-06:00",
          "endDate": "2020-03-26T09:30:00-06:00"
        },
        "numberOfTenderers": 3,
        "tenderers": [
          {
            "name": "string",
            "id": "string"
          }
        ],
        "documents": [
          {
            "id": "1",
            "documentType": "tenderNotice",
            "title": "Anuncio, convocatoria o invitación",
            "url": "http://guatecompras.gt/concursos/files/2385/11922052%40Anuncio%20de%20Convocatoria%20a%20ofertar%20licitacion.PDF",
            "datePublished": "2020-02-14T15:40:32-06:00",
            "format": "application/pdf",
            "language": "es"
          }
        ]
      },
      "awards": [
        {
          "id": "NOG-11922052",
          "title": "INSUMOS PARA CROMATOGRAFÍA DE GASES Y LÍQUIDA PARA LOS LABORATORIOS DE CRIMINALÍSTICA DEL INSTITUTO NACIONAL DE CIENCIAS FORENSES DE GUATEMALA",
          "status": "active",
          "date": "2020-04-13T10:30:00-06:00",
          "value": {
            "amount": 46961,
            "currency": "GTQ"
          },
          "suppliers": [
            {
              "id": "GT-NIT-93269846",
              "name": "EQUIPOS Y PRODUCTOS DE LABORATORIO, SOCIEDAD ANONIMA"
            }
          ]
        }
      ],
      "language": "es"
    }
  ]
}

=== open-contracting/standard/docs/examples/merging/example03-award.json
{
  "uri": "https://standard.open-contracting.org/examples/releases/ocds-23g63a01-200502-award.json",
  "publisher": {
    "name": "Zambia Public Procurement Authority"
  },
  "publishedDate": "2018-12-31T23:00:00Z",
  "version": "1.1",
  "releases": [
    {
      "language": "en",
      "ocid": "ocds-23g63a01-200502",
      "id": "ocds-23g63a01-200502-award",
      "tag": [
        "award"
      ],
      "date": "2018-12-31T23:00:00Z",
      "parties": [
        {
          "id": "ZM-PCR-001",
          "contactPoint": {
            "url": "http://www.Zamtel.zm",
            "faxNumber": "+260211256622",
            "telephone": "+260211333152",
            "email": "Customerservice@Zamtel.co.zm"
          },
          "identifier": {
            "id": "001",
            "scheme": "ZM-PCR",
            "legalName": "Zambia Telecommunications Company Limited"
          },
          "name": "Zambia Telecommunications Company Limited",
          "address": {
            "postalCode": "37000",
            "country": "ZM",
            "region": "ZM",
            "streetAddress": "Zamtel House, Corner Church and Chilubi Roads",
            "locality": "Lusaka"
          },
          "roles": [
            "buyer"
          ]
        },
        {
          "id": "ZM-PCR-104500",
          "name": "Joziel General Dealers Ltd",
          "contactPoint": {
            "telephone": "+260978552867"
          },
          "identifier": {
            "scheme": "ZM-PCR",
            "id": "104500",
            "uri": "https://www.pacra.org.zm/#/p/pacrasearch/",
            "legalName": "Joziel General Dealers Ltd"
          },
          "address": {
            "postalCode": "",
            "country": "ZM",
            "region": "ZM",
            "streetAddress": "Plot 17 Chaholi Road Rhodes Park",
            "locality": "Lusaka"
          },
          "roles": [
            "supplier"
          ]
        }
      ],
      "buyer": {
        "id": "ZM-PCR-001",
        "name": "Zambia Telecommunications Company Limited"
      },
      "awards": [
        {
          "status": "active",
          "description": "SUPPLY AND DELIVERY OF VARIOUS STATIONERY",
          "title": "SUPPLY AND DELIVERY OF VARIOUS STATIONERY",
          "items": [
            {
              "unit": {
                "name": "each"
              },
              "quantity": 30,
              "description": "Notebooks",
              "classification": {
                "scheme": "UNSPSC",
                "description": "Paper pads and notebooks",
                "id": "14111514"
              },
              "id": "14111514"
            },
            {
              "unit": {
                "name": "Ream"
              },
              "quantity": 130,
              "description": "Printing and writing paper",
              "classification": {
                "scheme": "UNSPSC",
                "description": "Printing and writing paper",
                "id": "14111500"
              },
              "id": "14111500"
            },
            {
              "unit": {
                "name": "packet"
              },
              "quantity": 100,
              "description": "Self adhesive note paper",
              "classification": {
                "scheme": "UNSPSC",
                "description": "Self adhesive note paper",
                "id": "14111530"
              },
              "id": "14111530"
            },
            {
              "unit": {
                "name": "each"
              },
              "quantity": 200,
              "description": "Folders",
              "classification": {
                "scheme": "UNSPSC",
                "description": "Folders",
                "id": "44122011"
              },
              "id": "44122011"
            }
          ],
          "suppliers": [
            {
              "id": "ZM-PCR-104500",
              "name": "Joziel General Dealers Ltd"
            }
          ],
          "value": {
            "currency": "ZMW",
            "amount": 13363.23
          },
          "date": "2018-12-31T06:40:57Z",
          "id": "1201"
        }
      ]
    }
  ]
}

=== open-contracting/standard/docs/examples/merging/deletions/object_tender.json
{
  "uri": "https://standard.open-contracting.org/examples/releases/ocds-k50g02-11-13-651832-tender.json",
  "publisher": {
    "name": "Colombia Compra Eficiente"
  },
  "publishedDate": "2011-10-14T16:26:49.000Z",
  "version": "1.2",
  "releases": [
    {
      "date": "2011-10-14T16:26:49.000Z",
      "ocid": "ocds-k50g02-11-13-651832",
      "id": "11-13-651832-tender",
      "tag": [
        "tender"
      ],
      "parties": [
        {
          "name": "CAUCA - ALCALDÍA MUNICIPIO DE MERCADERES",
          "roles": [
            "procuringEntity",
            "buyer"
          ],
          "address": {
            "country": "CO",
            "region": "Cauca",
            "locality": "Mercaderes"
          },
          "contactPoint": {
            "email": "derazo@example.com",
            "telephone": "152 2158746",
            "name": "DIEGO EDUARDO ERAZO GUERRERO"
          },
          "identifier": {
            "scheme": "CO-RUE",
            "id": "890701933",
            "legalName": "CAUCA - ALCALDÍA MUNICIPIO DE MERCADERES"
          },
          "id": "890701933"
        }
      ],
      "buyer": {
        "id": "890701933",
        "name": "CAUCA - ALCALDÍA MUNICIPIO DE MERCADERES"
      },
      "tender": {
        "id": "11-13-651832",
        "status": "active",
        "description": "CONSTRUCCIÓN DE OBRAS DE REHABILITACIÓN Y MANTENIMIENTO DE LA VÍA CARRETEABLE: VEREDA CURACAS-VEREDA LA MONJITA, EN UNA EXTENSIÓN DE SEIS (06) KILÓMETROS EN MUNICIPIO DE MERCADERES CAUCA.",
        "procurementMethod": "open",
        "submissionMethodDetails": "Municipio obtención: Mercaderes, Municipio entrega: Mercaderes, Municipio ejecución: No definido, Lugar aclaraciones: No definido",
        "procurementMethodDetails": "Contratación Mínima Cuantía",
        "value": {
          "amount": 5000000
        },
        "procuringEntity": {
          "id": "890701933",
          "name": "CAUCA - ALCALDÍA MUNICIPIO DE MERCADERES"
        },
        "procurementMethodRationale": "Ninguna",
        "tenderPeriod": {
          "startDate": "2011-10-14T16:22:00.000Z",
          "endDate": "2011-10-20T00:00:00.000Z"
        },
        "contractPeriod": {
          "startDate": "2011-11-20T09:00:00.000Z",
          "endDate": "2012-01-31T17:00:00.000Z"
        }
      }
    }
  ]
}

=== open-contracting/standard/docs/examples/merging/updates/tender3.json
{
  "uri": "https://standard.open-contracting.org/examples/releases/ocds-213czf-000-00002-01-tender-amendment.json",
  "publishedDate": "2016-02-05T10:30:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "https://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "extensions": [],
  "releases": [
    {
      "ocid": "ocds-213czf-000-00002",
      "id": "ocds-213czf-000-00002-01-tender-amendment",
      "date": "2016-02-05T10:30:00Z",
      "tag": [
        "tenderAmendment"
      ],
      "parties": [
        {
          "name": "Open Data Services",
          "identifier": {
            "scheme": "GB-COH",
            "id": "09506232",
            "legalName": "Open Data Services Co-operative",
            "uri": "https://opencorporates.com/companies/gb/09506232"
          },
          "roles": [
            "buyer"
          ],
          "id": "GB-COH-09506232"
        }
      ],
      "buyer": {
        "id": "GB-COH-09506232",
        "name": "Open Data Services"
      },
      "tender": {
        "id": "ocds-213czf-000-00002-01-tender",
        "title": "Data merging tool",
        "description": "Creation of a data merging tool. The tool should by written in Python. Proposals should be submitted by e-mail.",
        "status": "active",
        "value": {
          "amount": 2000,
          "currency": "USD"
        },
        "procurementMethod": "open",
        "awardCriteria": "bestProposal",
        "tenderPeriod": {
          "startDate": "2016-01-31T09:00:00Z",
          "endDate": "2016-02-20T18:00:00Z"
        },
        "awardPeriod": {
          "startDate": "2016-04-01T00:00:00Z",
          "endDate": "2016-06-01T23:59:59Z"
        },
        "amendments": [
          {
            "id": "amendment-1",
            "date": "2016-02-04T09:30:00Z",
            "rationale": "Based on feedback from potential bidders, the total budget was increased by $1000, and the deadline extended",
            "amendsReleaseID": "ocds-213czf-000-00002-01-tender",
            "releaseID": "ocds-213czf-000-00002-01-tender-amendment"
          }
        ]
      }
    }
  ]
}

=== open-contracting/standard/docs/examples/milestones/planning-tender-milestones.json
{
  "uri": "https://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-04-planning.json",
  "publishedDate": "2016-09-10T09:30:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "https://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "releases": [
    {
      "ocid": "ocds-213czf-000-00001",
      "id": "ocds-213czf-000-00001-04-planning",
      "date": "2016-09-10T09:30:00Z",
      "language": "en",
      "tag": [
        "planning"
      ],
      "initiationType": "tender",
      "planning": {
        "budget": {
          "id": "1.02.1.02.01.01.25.24.5.2.3.49.06",
          "amount": {
            "amount": 30000000,
            "currency": "IDR"
          },
          "project": "Konsultan Pengawas",
          "description": "APBD"
        },
        "milestones": [
          {
            "id": "1",
            "type": "preProcurement",
            "title": "Budget Plan",
            "status": "scheduled",
            "dueDate": "2016-09-19T23:29:03Z",
            "description": "Rencana Pengadaan Road Map"
          }
        ]
      },
      "tender": {
        "id": "planned",
        "status": "planned",
        "milestones": [
          {
            "id": 1,
            "title": "Tender notice publication estimation from procurement plan",
            "status": "scheduled",
            "type": "preProcurement",
            "dueDate": "2016-10-21T15:00:00Z"
          }
        ]
      }
    }
  ]
}

=== open-contracting/standard/docs/examples/organizational-units/moldova-tender.json
{
  "uri": "https://standard.open-contracting.org/release/ocds-b3wdp1-MD-1539840280133-1539840280205",
  "version": "1.1",
  "extensions": [
    "https://raw.githubusercontent.com/open-contracting-extensions/ocds_budget_breakdown_extension/master/extension.json",
    "https://standard.open-contracting.org/examples/extensions/ocds_divisionCode_extension/extension.json"
  ],
  "publisher": {
    "name": "M-Tender"
  },
  "license": "http://opendefinition.org/licenses/",
  "publicationPolicy": "https://standard.open-contracting.org/examples/publicationPolicy/",
  "publishedDate": "2018-10-18T05:24:39Z",
  "releases": [
    {
      "ocid": "ocds-b3wdp1-MD-1539840280133",
      "id": "ocds-b3wdp1-MD-1539840280133-1539840280205",
      "date": "2018-10-18T05:24:39Z",
      "tag": [
        "tender"
      ],
      "initiationType": "tender",
      "planning": {
        "budget": {
          "amount": {
            "amount": 1400000.0,
            "currency": "MDL"
          },
          "budgetBreakdown": [
            {
              "id": "ocds-b3wdp1-MD-1539784656442-FS-1539839968758",
              "description": "Piese consumabile pentru aparatele multifuncționale",
              "amount": {
                "amount": 1400000.0,
                "currency": "MDL"
              },
              "period": {
                "startDate": "2018-10-18T00:00:00Z",
                "endDate": "2018-12-31T00:00:00Z"
              }
            }
          ]
        }
      },
      "tender": {
        "id": "ocds-b3wdp1-MD-1539840280133",
        "title": "Piese consumabile pentru aparatele multifuncționale",
        "description": "Livrarea timp de 30 zile",
        "status": "active",
        "value": {
          "amount": 1400000.0,
          "currency": "MDL"
        },
        "procurementMethod": "open",
        "mainProcurementCategory": "goods",
        "hasEnquiries": false,
        "eligibilityCriteria": "Regulile generale privind naționalitatea și originea, precum și alte criterii de eligibilitate sunt enumerate în Ghidul practic privind procedurile de contractare a acțiunilor externe ale UE (PRAG)",
        "procuringEntity": {
          "name": "National Bank of Moldova - Chişinău Branch",
          "id": "MD-IDNO-1006601001182"
        },
        "items": [
          {
            "id": "1",
            "description": "Piese consumabile pentru aparatele multifuncționale",
            "classification": {
              "scheme": "CPV",
              "id": "30100000-0",
              "description": "Maşini, echipament şi accesorii de birou, cu excepţia computerelor, a imprimantelor şi a mobilierului"
            }
          }
        ]
      },
      "buyer": {
        "id": "MD-IDNO-1006601001182",
        "name": "National Bank of Moldova - Chişinău Branch"
      },
      "parties": [
        {
          "id": "MD-IDNO-1006601001182",
          "name": "National Bank of Moldova - Chişinău Branch",
          "identifier": {
            "scheme": "MD-IDNO",
            "id": "1006601001182",
            "legalName": "National Bank of Moldova"
          },
          "address": {
            "streetAddress": "1 Grigore Vieru Avenue",
            "locality": "Chişinău",
            "region": "Chişinău",
            "postalCode": "MD 2005",
            "countryName": "Moldova"
          },
          "contactPoint": {
            "email": "official@bnm.md",
            "telephone": "+373 22 822 606"
          },
          "roles": [
            "payer",
            "procuringEntity",
            "buyer"
          ],
          "details": {
            "divisionCode": "101"
          }
        }
      ]
    }
  ]
}
