=== open-contracting/standard/schema/release-package-schema.json
{
  "id": "https://standard.open-contracting.org/schema/1__1__5/release-package-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema for an Open Contracting Release Package",
  "description": "The release package contains a list of releases along with some publishing metadata.",
  "type": "object",
  "required": [
    "releases",
    "version"
  ],
  "properties": {
    "uri": {
      "title": "Package identifier",
      "description": "The URI of this package that identifies it uniquely in the world. Recommended practice is to use a dereferenceable URI, where a persistent copy of this package is available.",
      "type": "string",
      "format": "uri",
      "deprecated": {
        "description": "This field was used by the `packages` field in the record package schema, which is deprecated.",
        "deprecatedVersion": "1.2"
      }
    },
    "version": {
      "title": "OCDS schema version",
      "description": "The version of the OCDS schema used in this package, expressed as major.minor For example: 1.0 or 1.1",
      "type": "string",
      "pattern": "^(\\d+\\.)(\\d+)$"
    },
    "extensions": {
      "title": "OCDS extensions",
      "description": "An array of OCDS extensions used in this package, in which each array item is the URL of an extension.json file.",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "publishedDate": {
      "title": "Published date",
      "description": "The date that this package was published. If this package is generated 'on demand', this date should reflect the date of the last change to the underlying contents of the package.",
      "type": "string",
      "format": "date-time",
      "deprecated": {
        "description": "This field repeats the maximum `date` among the releases it contains.",
        "deprecatedVersion": "1.2"
      }
    },
    "releases": {
      "title": "Releases",
      "description": "An array of one or more OCDS releases.",
      "type": "array",
      "items": {
        "$ref": "https://standard.open-contracting.org/schema/1__1__5/release-schema.json"
      }
    },
    "publisher": {
      "title": "Publisher",
      "description": "Information to uniquely identify the publisher of this package.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the organization or department responsible for publishing this OCDS data.",
          "type": "string"
        },
        "scheme": {
          "title": "Scheme",
          "description": "The scheme that holds the unique identifiers used to identify the item being identified.",
          "type": [
            "string",
            "null"
          ]
        },
        "uid": {
          "title": "uid",
          "description": "The unique ID for this entity under the given ID scheme.",
          "type": [
            "string",
            "null"
          ]
        },
        "uri": {
          "title": "URI",
          "description": "A URI to identify the publisher.",
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      },
      "deprecated": {
        "description": "This field is deprecated in favor of the `publisher` field in the release schema.",
        "deprecatedVersion": "1.2"
      }
    },
    "license": {
      "title": "License",
      "description": "A link to the license that applies to the data in this package. A Public Domain Dedication or [Open Definition Conformant](https://opendefinition.org/licenses/) license is recommended. The canonical URI of the license should be used. Documents linked from this file may be under other license conditions.",
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": {
        "description": "It is not critical to distribute the license URL as data. The page linking to the data can express the license.",
        "deprecatedVersion": "1.2"
      }
    },
    "publicationPolicy": {
      "title": "Publication policy",
      "description": "A link to a document describing the publishers [publication policy](https://standard.open-contracting.org/{{version}}/{{lang}}/guidance/publish/#finalize-your-publication-policy).",
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": {
        "description": "It is not critical to distribute the publication policy URL as data. The page linking to the data can express the publication policy.",
        "deprecatedVersion": "1.2"
      }
    }
  }
}

=== open-contracting/standard/docs/examples/unsuccessful-tender-tender.json
{
  "uri": "https://www.contrataciones.gov.py/datos/api/v3/doc/ocds/releases/id/331547-servicio-rastreo-satelital-1-1511346066",
  "publishedDate": "2020-03-23T17:01:05Z",
  "publisher": {
    "name": "Dirección Nacional de Contrataciones Públicas, Paraguay"
  },
  "license": "https://creativecommons.org/licenses/by/4.0/",
  "publicationPolicy": "https://www.contrataciones.gov.py/datos/legal",
  "version": "1.1",
  "releases": [
    {
      "id": "331547-servicio-rastreo-satelital-1-1511346066",
      "tender": {
        "id": "331547-servicio-rastreo-satelital-1",
        "title": "SERVICIO DE RASTREO SATELITAL",
        "status": "unsuccessful",
        "awardCriteria": "priceOnly",
        "awardCriteriaDetails": "Por Total",
        "submissionMethod": [
          "inPerson"
        ],
        "submissionMethodDetails": "Lugar entrega ofertas: MUNICIPALIDAD DE LOMA PLATA || Lugar entrega bien: Según documento del llamado || Fecha entrega bien: Según documento del llamado",
        "eligibilityCriteria": "Restricciones: INHABILIDADES PREVISTAS EN EL ARTICULO 40 DE LA LEY 2051/03",
        "statusDetails": "Desierta",
        "enquiriesAddress": {
          "streetAddress": "MUNICIPALIDAD DE LOMA PLATA"
        },
        "mainProcurementCategoryDetails": "Bienes - Maquinarias, Equipos y herramientas mayores - Equipos de transporte",
        "hasEnquiries": false,
        "value": {
          "amount": 8100000,
          "currency": "PYG"
        },
        "tenderPeriod": {
          "startDate": "2017-05-03T09:53:46-04:00",
          "endDate": "2017-05-11T09:30:00-04:00",
          "durationInDays": 7
        },
        "awardPeriod": {
          "startDate": "2017-05-11T10:00:00-04:00"
        },
        "enquiryPeriod": {
          "endDate": "2017-05-05T11:00:00-04:00",
          "startDate": "2017-05-03T09:53:46-04:00",
          "durationInDays": 2
        },
        "mainProcurementCategory": "goods",
        "procurementMethod": "open",
        "procurementMethodDetails": "Contratación Directa",
        "procuringEntity": {
          "id": "DNCP-SICP-CODE-321",
          "name": "Municipalidad de Loma Plata"
        },
        "lots": [
          {
            "id": "+GmottIGrAE=",
            "title": "1 - SERVICIO DE RASTREO SATELITAL",
            "status": "unsuccessful",
            "value": {
              "amount": 8100000,
              "currency": "PYG"
            }
          }
        ],
        "items": [
          {
            "id": "+PMxGSG2jUzCpFMtx0fwgg==",
            "description": "Servicio de Rastreo Satelital",
            "classification": {
              "scheme": "catalogoNivel5DNCP",
              "id": "92121701-002",
              "description": "Servicio de Rastreo Satelital",
              "uri": "https://www.contrataciones.gov.py/datos/api/v3/doc/itemClassification/n5/92121701-002"
            },
            "quantity": 6,
            "unit": {
              "name": "Unidad",
              "id": "UNI",
              "value": {
                "amount": 1350000,
                "currency": "PYG"
              }
            },
            "relatedLot": "+GmottIGrAE="
          }
        ]
      },
      "language": "es",
      "ocid": "ocds-03ad3f-331547-1",
      "date": "2017-11-22T10:21:06-04:00",
      "initiationType": "tender",
      "buyer": {
        "id": "DNCP-SICP-CODE-321",
        "name": "Municipalidad de Loma Plata"
      },
      "parties": [
        {
          "id": "DNCP-SICP-CODE-321",
          "name": "Municipalidad de Loma Plata",
          "identifier": {
            "scheme": "DNCP-SICP-CODE",
            "id": "321",
            "legalName": "Municipalidad de Loma Plata"
          },
          "contactPoint": {
            "email": "uoc_municip_lomaplata@hotmail.com",
            "name": "Armanda  Armanda Acosta",
            "telephone": "0492  - 252163"
          },
          "roles": [
            "buyer",
            "procuringEntity"
          ]
        }
      ],
      "tag": [
        "tender"
      ]
    }
  ]
}

=== open-contracting/standard/docs/examples/organizational-units/paraguay-planning.json
{
  "uri": "https://standard.open-contracting.org/examples/release/ocds-03ad3f-373449-1/1",
  "publishedDate": "2019-12-05T12:36:58-04:00",
  "publisher": {
    "name": "Dirección Nacional de Contrataciones Públicas, Paraguay"
  },
  "license": "https://creativecommons.org/licenses/by/4.0/",
  "publicationPolicy": "https://standard.open-contracting.org/examples/publicationPolicy/",
  "version": "1.1",
  "releases": [
    {
      "language": "es",
      "ocid": "ocds-03ad3f-373449-1",
      "id": "ocds-03ad3f-373449-1/1",
      "date": "2019-12-05T12:36:58-04:00",
      "initiationType": "tender",
      "tag": [
        "planning"
      ],
      "buyer": {
        "id": "PY-RUC-80001180-5",
        "name": "Facultad de Ciencias Médicas - Hospital de Clínicas"
      },
      "parties": [
        {
          "id": "PY-RUC-80001180-5",
          "name": "Facultad de Ciencias Médicas - Hospital de Clínicas",
          "identifier": {
            "scheme": "PY-RUC",
            "id": "80001180-5",
            "legalName": "FACULTAD DE CIENCIAS MEDICAS"
          },
          "roles": [
            "buyer",
            "procuringEntity",
            "payer"
          ],
          "address": {
            "streetAddress": "AVDA. MCAL LOPEZ ESQ. CORONEL CAZAL",
            "locality": "San Lorenzo",
            "region": "Central",
            "countryName": "Paraguay"
          },
          "contactPoint": {
            "name": "LIC. LIZ RAQUEL DUARTE QUINTANA",
            "telephone": "+595 21 683.930 INT. 102",
            "email": "uoc@med.una.py"
          }
        }
      ],
      "planning": {
        "budget": {
          "description": "Nombre de la Licitación ADQUISICION DE REACTIVOS E INSUMOS DE HEMOCENTRO Y UMT DEL HOSPITAL DE CLINICAS ? AD RERENDUM PRESUPUESTO 2020",
          "amount": {
            "currency": "PYG",
            "amount": 950000000
          }
        }
      },
      "tender": {
        "id": "359402",
        "description": "ADQUISICION DE REACTIVOS E INSUMOS DE HEMOCENTRO Y UMT DEL HOSPITAL DE CLINICAS ? AD RERENDUM PRESUPUESTO 2020",
        "status": "planned",
        "procurementMethod": "open",
        "mainProcurementCategory": "goods",
        "procuringEntity": {
          "id": "PY-RUC-80001180-5",
          "name": "Facultad de Ciencias Médicas - Hospital de Clínicas"
        },
        "value": {
          "amount": 895351000,
          "currency": "PYG"
        },
        "tenderPeriod": {
          "startDate": "2019-01-13T08:00:00-04:00",
          "endDate": "2019-01-28T11:00:00-04:00"
        },
        "items": [
          {
            "id": "41116105",
            "description": "Anti A Monoclonal",
            "quantity": 110,
            "unit": {
              "name": "Unidad",
              "value": {
                "amount": 44100,
                "currency": "PYG"
              }
            },
            "classification": {
              "scheme": "UNSPSC",
              "id": "41116105",
              "description": "Reactivos o soluciones quimicos"
            }
          },
          {
            "id": "41116002",
            "description": "REACTIVO PARA HIV",
            "quantity": 11500,
            "unit": {
              "name": "Unidad",
              "value": {
                "amount": 27000,
                "currency": "PYG"
              }
            },
            "classification": {
              "scheme": "UNSPSC",
              "id": "41116002",
              "description": "Reactivo para HIV"
            }
          },
          {
            "id": "42222308",
            "description": "Bolsa colectora de sangre",
            "quantity": 2000,
            "unit": {
              "name": "Unidad",
              "value": {
                "amount": 290000,
                "currency": "PYG"
              }
            },
            "classification": {
              "scheme": "UNSPSC",
              "id": "42222308",
              "description": "Bolsa colectora de sangre"
            }
          }
        ]
      }
    }
  ]
}

=== open-contracting/standard/docs/examples/organization-classification/fictional_wob_organization_classification.json
{
  "publishedDate": "2020-02-01T17:10:14+05:45",
  "publisher": {
    "name": "Ciudad Ficticia"
  },
  "extensions": [
    "https://raw.githubusercontent.com/open-contracting-extensions/ocds_organizationClassification_extension/master/extension.json"
  ],
  "version": "1.1",
  "uri": "https://standard.open-contracting.org/examples/release/ocds-213czf-col-cf/1111",
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/fictional_publication_policy_url",
  "releases": [
    {
      "ocid": "ocds-213czf-col-cf/1111",
      "id": "ocds-213czf-col-cf/1111-02-award",
      "language": "es",
      "date": "2020-01-04T13:18:31+05:45",
      "parties": [
        {
          "id": "CF-CDC-A564321",
          "name": "Empresa de mujeres uno",
          "identifier": {
            "scheme": "CF-CDC",
            "id": "A564321"
          },
          "roles": [
            "supplier"
          ],
          "details": {
            "classifications": [
              {
                "name": "Negocio propiedad de mujeres",
                "id": "NPDM",
                "scheme": "COL-CF-MON"
              }
            ]
          }
        }
      ],
      "awards": [
        {
          "suppliers": [
            {
              "name": "Empresa de mujeres uno",
              "id": "CF-CDC-A564321"
            }
          ],
          "status": "active",
          "date": "2019-01-01T00:00:00+05:45",
          "id": "ocds-213czf-col-cf-awards/1",
          "title": "Servicios de proyectos de datos abiertos de la ciudad"
        }
      ],
      "tag": [
        "award"
      ]
    }
  ]
}

=== open-contracting/standard/docs/examples/easy_releases/worked_example2/contract.json
{
  "uri": "https://standard.open-contracting.org/examples/",
  "version": "1.1",
  "publisher": {
    "uid": "80048717-6",
    "name": "Direccion Nacional de Contrataciones PÃºblicas",
    "scheme": "PY-RUC",
    "uri": "https://standard.open-contracting.org/examples/"
  },
  "publishedDate": "2020-01-11T07:53:50Z",
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "releases": [
    {
      "date": "2020-01-11T07:53:50Z",
      "ocid": "ocds-213czf-371630",
      "id": "ocds-213czf-371630/1a87b0662990c66e140e62e813165107",
      "tag": [
        "tender",
        "award",
        "contract"
      ],
      "parties": [
        {
          "id": "PY-RUC-80023736-6",
          "name": "City Hall of Juan de Mena",
          "identifier": {
            "scheme": "PY-RUC",
            "id": "80023736-6"
          }
        },
        {
          "id": "PY-RUC-80020095-0",
          "name": "Bosques del Parana SRL",
          "identifier": {
            "scheme": "PY-RUC",
            "id": "80020095-0"
          }
        }
      ],
      "buyer": {
        "id": "PY-RUC-80023736-6",
        "name": "City Hall of Juan de Mena"
      },
      "tender": {
        "id": "101",
        "title": "Cleaning services",
        "description": "Cleaning services for the City Hall, from 01/2020 to 12/2020",
        "status": "active",
        "procurementMethod": "direct",
        "value": {
          "amount": 144300000,
          "currency": "PYG"
        },
        "tenderPeriod": {
          "startDate": "2019-12-14T08:00:00Z",
          "endDate": "2019-12-14T08:30:00Z"
        }
      },
      "awards": [
        {
          "id": "371630/100",
          "date": "2019-12-26T14:00:00Z",
          "title": "Cleaning services",
          "description": "Cleaning services for the City Hall",
          "value": {
            "amount": 144300000,
            "currency": "PYG"
          },
          "suppliers": [
            {
              "id": "PY-RUC-80020095-0",
              "name": "Bosques del Parana SRL"
            }
          ]
        }
      ],
      "contracts": [
        {
          "id": "371630/100",
          "awardID": "371630/100",
          "title": "Cleaning services",
          "description": "Cleaning services for the City Hall",
          "status": "active",
          "value": {
            "amount": 116400000,
            "currency": "PYG"
          },
          "dateSigned": "2019-01-10T10:00:00Z",
          "period": {
            "startDate": "2019-01-15T08:00:00Z",
            "endDate": "2020-01-14T17:00:00Z"
          }
        }
      ]
    }
  ]
}

=== open-contracting/standard/docs/examples/contractAmendment.json
{
  "uri": "https://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-07-contractAmendment.json",
  "publishedDate": "2011-04-05T13:30:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "https://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "extensions": [],
  "releases": [
    {
      "ocid": "ocds-213czf-000-00001",
      "id": "ocds-213czf-000-00001-07-contractAmendment",
      "date": "2011-04-05T13:30:00Z",
      "language": "en",
      "tag": [
        "contractAmendment"
      ],
      "initiationType": "tender",
      "parties": [
        {
          "identifier": {
            "scheme": "GB-LAC",
            "id": "E09000003",
            "legalName": "London Borough of Barnet",
            "uri": "http://www.barnet.gov.uk/"
          },
          "name": "London Borough of Barnet",
          "address": {
            "streetAddress": "4, North London Business Park, Oakleigh Rd S",
            "locality": "London",
            "region": "London",
            "postalCode": "N11 1NP",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Procurement Team",
            "email": "procurement-team@example.com",
            "telephone": "01234 345 346",
            "faxNumber": "01234 345 345",
            "url": "http://example.com/contact/"
          },
          "roles": [
            "buyer"
          ],
          "id": "GB-LAC-E09000003"
        },
        {
          "identifier": {
            "scheme": "GB-COH",
            "id": "00395826",
            "legalName": "Balfour Beatty plc",
            "uri": "https://opencorporates.com/companies/gb/01881683"
          },
          "additionalIdentifiers": [
            {
              "scheme": "GB-VAT",
              "id": "217967235"
            }
          ],
          "name": "Balfour Beatty",
          "address": {
            "streetAddress": "5 Churchill Place",
            "locality": "London",
            "region": "London",
            "postalCode": "E14 5HU",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Contracts Team",
            "email": "help@balfourbeatty.com",
            "telephone": "44 (0)20 7216 6800",
            "faxNumber": "44 (0)20 7216 6800"
          },
          "roles": [
            "supplier"
          ],
          "id": "GB-COH-00395826"
        }
      ],
      "buyer": {
        "id": "GB-LAC-E09000003",
        "name": "London Borough of Barnet"
      },
      "awards": [
        {
          "id": "ocds-213czf-000-00001-award-01",
          "title": "Award of contract to build new cycle lanes in the centre of town.",
          "description": "Balfour Beatty Plc has been awarded the contract to build new cycle lanes in the centre of town.",
          "status": "active",
          "date": "2010-05-10T10:30:00Z",
          "value": {
            "amount": 11000000,
            "currency": "GBP"
          },
          "suppliers": [
            {
              "id": "GB-COH-00395826",
              "name": "Balfour Beatty"
            }
          ],
          "items": [
            {
              "id": "0001",
              "description": "string",
              "classification": {
                "scheme": "CPV",
                "id": "45233130",
                "description": "Construction work for highways",
                "uri": "http://cpv.data.ac.uk/code-45233130"
              },
              "additionalClassifications": [
                {
                  "scheme": "CPV",
                  "id": "45233162-2",
                  "description": "Cycle path construction work",
                  "uri": "http://cpv.data.ac.uk/code-45233162.html"
                }
              ],
              "quantity": 8,
              "unit": {
                "name": "Miles",
                "value": {
                  "amount": 137000,
                  "currency": "GBP"
                }
              }
            }
          ],
          "contractPeriod": {
            "startDate": "2010-07-01T00:00:00Z",
            "endDate": "2011-08-01T23:59:00Z"
          },
          "documents": [
            {
              "id": "0007",
              "documentType": "awardNotice",
              "title": "Award notice",
              "description": "Award of contract to build new cycle lanes in the centre of town to Balfour Beatty Plc.",
              "url": "http://example.com/tender-notices/ocds-213czf-000-00001-04.html",
              "datePublished": "2010-05-10T10:30:00Z",
              "format": "text/html",
              "language": "en"
            }
          ]
        }
      ],
      "contracts": [
        {
          "id": "ocds-213czf-000-00001-contract-01",
          "awardID": "ocds-213czf-000-00001-award-01",
          "title": "Contract to build new cycle lanes in the centre of town.",
          "description": "Contract monitoring for cycle lane construction.",
          "status": "active",
          "period": {
            "startDate": "2010-07-01T00:00:00Z",
            "endDate": "2011-10-30T23:59:00Z"
          },
          "value": {
            "amount": 13500000,
            "currency": "GBP"
          },
          "items": [
            {
              "id": "0001",
              "description": "string",
              "classification": {
                "scheme": "CPV",
                "id": "45233130",
                "description": "Construction work for highways",
                "uri": "http://cpv.data.ac.uk/code-45233130"
              },
              "additionalClassifications": [
                {
                  "scheme": "CPV",
                  "id": "45233162-2",
                  "description": "Cycle path construction work",
                  "uri": "http://cpv.data.ac.uk/code-45233162.html"
                }
              ],
              "quantity": 8,
              "unit": {
                "name": "Miles",
                "value": {
                  "amount": 137000,
                  "currency": "GBP"
                }
              }
            }
          ],
          "dateSigned": "2015-06-10T14:23:12Z",
          "documents": [
            {
              "id": "0008",
              "documentType": "contractSigned",
              "title": "Signed Contract",
              "description": "The Signed Contract for Cycle Path Construction",
              "url": "http://example.com/contracts/ocds-213czf-000-00001",
              "datePublished": "2015-06-10T16:43:12Z",
              "format": "application/pdf",
              "language": "en"
            }
          ],
          "amendments": [
            {
              "date": "2011-04-05T13:30:00Z",
              "rationale": "Due to unforeseen complications, a contract extension is issued to cover the additional time and cost required to complete the works.",
              "id": "0001",
              "amendsReleaseID": "ocds-213czf-000-00001-06-implementation",
              "releaseID": "ocds-213czf-000-00001-07-contractAmendment"
            }
          ]
        }
      ]
    }
  ]
}

=== open-contracting/standard/docs/examples/pre-qualification/pre-qualification-package.json
{
  "uri": "http://example.com",
  "publisher": {
    "name": "Open Data Services Co-operative Ltd"
  },
  "publishedDate": "2019-02-22T00:00:00Z",
  "version": "1.1",
  "releases": [
    {
      "ocid": "ocds-213czf-b744019f-c7c3-4f78-8811-1845d0c18c8d",
      "id": "2019/S 040-090873",
      "date": "2019-02-22T00:00:00Z",
      "tag": [
        "tender"
      ],
      "initiationType": "tender",
      "buyer": {
        "name": "Bank of England"
      },
      "tender": {
        "id": "2019/S 040-090873",
        "description": "The Bank of England has a requirement for FM (M&E, security and cleaning) services at its site in Roehampton, SW15 5JQ.",
        "classification": {
          "scheme": "CPV",
          "id": "71300000"
        },
        "tenderPeriod": {
          "endDate": "2019-04-05T12:00:00Z"
        },
        "procurementMethod": "selective"
      }
    }
  ]
}
