=== open-contracting/standard/schema/release-package-schema.json
{
  "id": "https://standard.open-contracting.org/schema/1__1__5/release-package-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema for an Open Contracting Release Package",
  "description": "The release package contains a list of releases along with some publishing metadata.",
  "type": "object",
  "required": [
    "releases",
    "version"
  ],
  "properties": {
    "uri": {
      "title": "Package identifier",
      "description": "The URI of this package that identifies it uniquely in the world. Recommended practice is to use a dereferenceable URI, where a persistent copy of this package is available.",
      "type": "string",
      "format": "uri",
      "deprecated": {
        "description": "This field was used by the `packages` field in the record package schema, which is deprecated.",
        "deprecatedVersion": "1.2"
      }
    },
    "version": {
      "title": "OCDS schema version",
      "description": "The version of the OCDS schema used in this package, expressed as major.minor For example: 1.0 or 1.1",
      "type": "string",
      "pattern": "^(\\d+\\.)(\\d+)$"
    },
    "extensions": {
      "title": "OCDS extensions",
      "description": "An array of OCDS extensions used in this package, in which each array item is the URL of an extension.json file.",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "publishedDate": {
      "title": "Published date",
      "description": "The date that this package was published. If this package is generated 'on demand', this date should reflect the date of the last change to the underlying contents of the package.",
      "type": "string",
      "format": "date-time",
      "deprecated": {
        "description": "This field repeats the maximum `date` among the releases it contains.",
        "deprecatedVersion": "1.2"
      }
    },
    "releases": {
      "title": "Releases",
      "description": "An array of one or more OCDS releases.",
      "type": "array",
      "items": {
        "$ref": "https://standard.open-contracting.org/schema/1__1__5/release-schema.json"
      }
    },
    "publisher": {
      "title": "Publisher",
      "description": "Information to uniquely identify the publisher of this package.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the organization or department responsible for publishing this OCDS data.",
          "type": "string"
        },
        "scheme": {
          "title": "Scheme",
          "description": "The scheme that holds the unique identifiers used to identify the item being identified.",
          "type": [
            "string",
            "null"
          ]
        },
        "uid": {
          "title": "uid",
          "description": "The unique ID for this entity under the given ID scheme.",
          "type": [
            "string",
            "null"
          ]
        },
        "uri": {
          "title": "URI",
          "description": "A URI to identify the publisher.",
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        }
      },
      "deprecated": {
        "description": "This field is deprecated in favor of the `publisher` field in the release schema.",
        "deprecatedVersion": "1.2"
      }
    },
    "license": {
      "title": "License",
      "description": "A link to the license that applies to the data in this package. A Public Domain Dedication or [Open Definition Conformant](https://opendefinition.org/licenses/) license is recommended. The canonical URI of the license should be used. Documents linked from this file may be under other license conditions.",
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": {
        "description": "It is not critical to distribute the license URL as data. The page linking to the data can express the license.",
        "deprecatedVersion": "1.2"
      }
    },
    "publicationPolicy": {
      "title": "Publication policy",
      "description": "A link to a document describing the publishers [publication policy](https://standard.open-contracting.org/{{version}}/{{lang}}/guidance/publish/#finalize-your-publication-policy).",
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "deprecated": {
        "description": "It is not critical to distribute the publication policy URL as data. The page linking to the data can express the publication policy.",
        "deprecatedVersion": "1.2"
      }
    }
  }
}

=== open-contracting/standard/docs/examples/merging/deletions/array_awardAmendment.json
{
  "uri": "https://standard.open-contracting.org/examples/releases/ocds-23g63a01-200502-awardAmendment.json",
  "publisher": {
    "name": "Zambia Public Procurement Authority"
  },
  "publishedDate": "2019-01-21T09:00:00Z",
  "version": "1.1",
  "releases": [
    {
      "ocid": "ocds-23g63a01-200502",
      "id": "ocds-23g63a01-200502-awardAmendment",
      "tag": [
        "awardAmendment"
      ],
      "date": "2019-01-21T09:00:00Z",
      "parties": [
        {
          "id": "ZM-PCR-001",
          "contactPoint": {
            "url": "http://www.Zamtel.zm",
            "faxNumber": "+260211256622",
            "telephone": "+260211333152",
            "email": "Customerservice@Zamtel.co.zm"
          },
          "identifier": {
            "id": "001",
            "scheme": "ZM-PCR",
            "legalName": "Zambia Telecommunications Company Limited"
          },
          "name": "Zambia Telecommunications Company Limited",
          "address": {
            "postalCode": "37000",
            "country": "ZM",
            "region": "ZM",
            "streetAddress": "Zamtel House, Corner Church and Chilubi Roads",
            "locality": "Lusaka"
          },
          "roles": [
            "buyer"
          ]
        },
        {
          "id": "ZM-PCR-104500",
          "name": "Joziel General Dealers Ltd",
          "contactPoint": {
            "telephone": "+260978552867"
          },
          "identifier": {
            "scheme": "ZM-PCR",
            "id": "104500",
            "uri": "https://www.pacra.org.zm/#/p/pacrasearch/",
            "legalName": "Joziel General Dealers Ltd"
          },
          "address": {
            "postalCode": "",
            "country": "ZM",
            "region": "ZM",
            "streetAddress": "Plot 17 Chaholi Road Rhodes Park",
            "locality": "Lusaka"
          },
          "roles": [
            "supplier"
          ]
        }
      ],
      "buyer": {
        "id": "ZM-PCR-001",
        "name": "Zambia Telecommunications Company Limited"
      },
      "awards": [
        {
          "status": "active",
          "description": "SUPPLY AND DELIVERY OF VARIOUS STATIONERY",
          "title": "SUPPLY AND DELIVERY OF VARIOUS STATIONERY",
          "items": [
            {
              "unit": {
                "name": "each"
              },
              "quantity": 30,
              "description": "Notebooks",
              "classification": {
                "scheme": "UNSPSC",
                "description": "Paper pads and notebooks",
                "id": "14111514"
              },
              "id": "14111514"
            },
            {
              "unit": {
                "name": null
              },
              "quantity": null,
              "description": null,
              "classification": {
                "scheme": null,
                "description": null,
                "id": null
              },
              "id": "14111500"
            },
            {
              "unit": {
                "name": "packet"
              },
              "quantity": 100,
              "description": "Self adhesive note paper",
              "classification": {
                "scheme": "UNSPSC",
                "description": "Self adhesive note paper",
                "id": "14111530"
              },
              "id": "14111530"
            },
            {
              "unit": {
                "name": "each"
              },
              "quantity": 200,
              "description": "Folders",
              "classification": {
                "scheme": "UNSPSC",
                "description": "Folders",
                "id": "44122011"
              },
              "id": "44122011"
            },
            {
              "unit": {
                "name": "Ream"
              },
              "quantity": 150,
              "description": "Computer printout paper",
              "classification": {
                "scheme": "UNSPSC",
                "description": "Computer printout paper",
                "id": "14111506"
              },
              "id": "14111506"
            },
            {
              "unit": {
                "name": "Ream"
              },
              "quantity": 20,
              "description": "Writing paper",
              "classification": {
                "scheme": "UNSPSC",
                "description": "Writing paper",
                "id": "14111511"
              },
              "id": "14111511"
            }
          ],
          "suppliers": [
            {
              "id": "ZM-PCR-104500",
              "name": "Joziel General Dealers Ltd"
            }
          ],
          "value": {
            "currency": "ZMW",
            "amount": 13452.0
          },
          "amendments": [
            {
              "id": "001",
              "description": "One awarded item has been removed in favor of other two ones.",
              "rationale": "Items have been changed after negotiations with the supplier.",
              "amendsReleaseID": "ocds-23g63a01-200502-award"
            }
          ],
          "date": "2018-12-31T06:40:57Z",
          "id": "1201"
        }
      ]
    }
  ]
}

=== open-contracting/standard/docs/examples/milestones/implementation_milestones_scheduled.json
{
  "uri": "https://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-05-contract.json",
  "publishedDate": "2011-01-10T09:30:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "https://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "releases": [
    {
      "ocid": "ocds-213czf-000-00001",
      "id": "ocds-213czf-000-00001-06-implementation-milestones-1",
      "date": "2018-01-05T09:30:00Z",
      "tag": [
        "implementation"
      ],
      "parties": [
        {
          "identifier": {
            "scheme": "GB-LAC",
            "id": "E09000003",
            "legalName": "London Borough of Barnet"
          },
          "name": "London Borough of Barnet",
          "roles": [
            "buyer"
          ],
          "id": "GB-LAC-E09000003"
        }
      ],
      "buyer": {
        "id": "GB-LAC-E09000003",
        "name": "London Borough of Barnet"
      },
      "contracts": [
        {
          "id": "ocds-213czf-000-00001-contract-01",
          "awardID": "ocds-213czf-000-00001-award-01",
          "title": "Contract to build new cycle lanes in the centre of town.",
          "implementation": {
            "milestones": [
              {
                "id": "1",
                "title": "project started",
                "type": "delivery",
                "code": "commencement",
                "dueDate": "2018-03-19T00:00:00Z",
                "status": "scheduled"
              },
              {
                "id": "2",
                "title": "project completed",
                "type": "delivery",
                "code": "completion",
                "dueDate": "2018-12-31T00:00:00Z",
                "status": "scheduled"
              }
            ]
          }
        }
      ]
    }
  ]
}

=== open-contracting/standard/docs/examples/pre-qualification/pre-selection-package.json
{
  "uri": "http://example.com",
  "publisher": {
    "name": "Open Data Services Co-operative Ltd"
  },
  "publishedDate": "2020-01-17T00:00:00Z",
  "version": "1.1",
  "extensions": [
    "https://raw.githubusercontent.com/open-contracting-extensions/ocds_selectionCriteria_extension/master/extension.json"
  ],
  "releases": [
    {
      "ocid": "ocds-213czf-2d4d7408-4743-4d04-b57d-18d5ecdd8ef8",
      "id": "2020/S 014-028681",
      "date": "2020-01-17T00:00:00Z",
      "tag": [
        "tender"
      ],
      "initiationType": "tender",
      "buyer": {
        "name": "National Nuclear Laboratory"
      },
      "tender": {
        "id": "2020/S 014-028681",
        "description": "The NNL Preston Laboratory is located on the Springfields Fuels Ltd (SFL) site near Preston, Lancashire. NNL are carrying out their regulatory responsibilities as a Dutyholder to protect nuclear materials (NM) and other radioactive materials (ORM) from theft and sabotage by malicious threats. The facility operates under an approved nuclear site security plan in accordance with the Nuclear Industries Security Regulations (2003). This project is to further upgrade the physical protection system (PPS) arrangements at Preston Laboratory.",
        "classification": {
          "scheme": "CPV",
          "id": "35120000"
        },
        "tenderPeriod": {
          "endDate": "2020-02-17T12:00:00Z"
        },
        "procurementMethod": "selective",
        "selectionCriteria": {
          "criteria": [
            {
              "description": "The SSQ will be utilised. Responses to the SSQ will either be pass/fail, scored or for information only. The five top scoring suppliers will be taken through to award stage, following successful completion of a security audit. Further details can be found within the procurement documentation."
            }
          ]
        }
      }
    }
  ]
}

=== open-contracting/standard/docs/examples/organization-identifiers.json
{
  "uri": "https://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-04-award.json",
  "publishedDate": "2010-05-10T09:30:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "https://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "extensions": [],
  "releases": [
    {
      "ocid": "ocds-213czf-000-00001",
      "id": "ocds-213czf-000-00001-04-award",
      "date": "2010-05-10T09:30:00Z",
      "language": "en",
      "tag": [
        "award"
      ],
      "initiationType": "tender",
      "parties": [
        {
          "identifier": {
            "scheme": "GB-LAC",
            "id": "E09000003",
            "legalName": "London Borough of Barnet"
          },
          "name": "London Borough of Barnet",
          "address": {
            "streetAddress": "4, North London Business Park, Oakleigh Rd S",
            "locality": "London",
            "region": "London",
            "postalCode": "N11 1NP",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Procurement Team",
            "email": "procurement-team@example.com",
            "telephone": "01234 345 346",
            "faxNumber": "01234 345 345",
            "url": "http://www.barnet.gov.uk/"
          },
          "roles": [
            "buyer"
          ],
          "id": "GB-LAC-E09000003"
        },
        {
          "identifier": {
            "scheme": "GB-COH",
            "id": "04336774",
            "legalName": "IBM LP LIMITED",
            "uri": "https://opencorporates.com/companies/gb/04336774"
          },
          "additionalIdentifiers": [
            {
              "scheme": "GB-VAT",
              "id": "GB107328000",
              "legalName": "IBM UK LIMITED"
            },
            {
              "id": "100012",
              "scheme": "X-GB-CF"
            }
          ],
          "name": "IBM",
          "address": {
            "streetAddress": "76, 78 Upper Ground",
            "locality": "London",
            "region": "London",
            "postalCode": "SE1 9PZ",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Contracts Team",
            "email": "ibm_crc@uk.ibm.com",
            "telephone": "+44 (0) 370 909 9997"
          },
          "roles": [
            "supplier"
          ],
          "id": "GB-COH-04336774"
        }
      ],
      "buyer": {
        "id": "GB-LAC-E09000003",
        "name": "London Borough of Barnet"
      },
      "awards": [
        {
          "id": "ocds-213czf-000-00001-award-01",
          "title": "Licenses for analytical software",
          "description": "IBM has been awarded for licenses for the SPSS Statistics software",
          "status": "pending",
          "date": "2010-05-10T09:30:00Z",
          "value": {
            "amount": 1096000,
            "currency": "GBP"
          },
          "suppliers": [
            {
              "id": "GB-COH-04336774",
              "name": "IBM"
            }
          ],
          "items": [
            {
              "id": "0001",
              "description": "string",
              "classification": {
                "scheme": "CPV",
                "id": "48218000",
                "description": "Construction work for highways",
                "uri": "http://cpv.data.ac.uk/code-48218000"
              },
              "quantity": 8,
              "unit": {
                "name": "unit",
                "value": {
                  "amount": 137000,
                  "currency": "GBP"
                }
              }
            }
          ],
          "contractPeriod": {
            "startDate": "2010-07-01T00:00:00Z",
            "endDate": "2011-07-31T23:59:00Z"
          }
        }
      ]
    }
  ]
}

=== open-contracting/standard/docs/examples/minimal_updates/tenderUpdate.json
{
  "uri": "https://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-03-tenderAmendment.json",
  "publishedDate": "2010-03-20T09:45:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "https://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "extensions": [],
  "releases": [
    {
      "ocid": "ocds-213czf-000-00001",
      "id": "ocds-213czf-000-00001-03-tenderUpdate",
      "date": "2010-03-20T09:45:00Z",
      "language": "en",
      "tag": [
        "tenderUpdate"
      ],
      "initiationType": "tender",
      "parties": [
        {
          "identifier": {
            "scheme": "GB-LAC",
            "id": "E09000003",
            "legalName": "London Borough of Barnet",
            "uri": "http://www.barnet.gov.uk/"
          },
          "name": "London Borough of Barnet",
          "address": {
            "streetAddress": "4, North London Business Park, Oakleigh Rd S",
            "locality": "London",
            "region": "London",
            "postalCode": "N11 1NP",
            "countryName": "United Kingdom"
          },
          "contactPoint": {
            "name": "Procurement Team",
            "email": "procurement-team@example.com",
            "telephone": "01234 345 346",
            "faxNumber": "01234 345 345",
            "url": "http://example.com/contact/"
          },
          "roles": [
            "procuringEntity",
            "buyer"
          ],
          "id": "GB-LAC-E09000003"
        }
      ],
      "buyer": {
        "id": "GB-LAC-E09000003",
        "name": "London Borough of Barnet"
      },
      "tender": {
        "id": "ocds-213czf-000-00001-01-tender",
        "documents": [
          {
            "id": "0006",
            "documentType": "enquiryResponses",
            "title": "Enquiry Responses",
            "description": "Responses to enquiries asked by interested parties.",
            "url": "http://example.com/enquiry-response/ocds-213czf-000-00001-01.html",
            "datePublished": "2010-03-20T11:30:15Z",
            "format": "text/html",
            "language": "en"
          }
        ]
      }
    }
  ]
}

=== open-contracting/standard/docs/examples/people-in-organizations/moldova.json
{
  "publishedDate": "2020-04-07T21:33:00Z",
  "publisher": {
    "name": "Public Procurement Agency"
  },
  "uri": "https://standard.open-contracting.org/examples/ocds-b3wdp1-MD-123456789/ocds-b3wdp1-MD-123456789-3",
  "version": "1.1",
  "license": "https://creativecommons.org/publicdomain/",
  "publicationPolicy": "http://bit.ly/OCDS11-publication-policy",
  "releases": [
    {
      "date": "2019-01-11T06:17:02.000Z",
      "ocid": "ocds-b3wdp1-MD-123456789",
      "id": "ocds-b3wdp1-MD-123456789/3",
      "initiationType": "tender",
      "tag": [
        "award"
      ],
      "parties": [
        {
          "id": "MD-IDNO-1007601003150",
          "name": "Primaria s. Elizaveta",
          "identifier": {
            "scheme": "MD-IDNO",
            "id": "1007601003150",
            "legalName": "Primaria s. Elizaveta"
          },
          "roles": [
            "buyer"
          ],
          "address": {
            "streetAddress": "str. Stefan cel Mare 22",
            "locality": "s.Elizaveta"
          }
        },
        {
          "id": "MD-IDNO-1002600003240",
          "name": "Slavena Lux",
          "identifier": {
            "scheme": "MD-IDNO",
            "id": "1002600003240"
          },
          "roles": [
            "supplier"
          ],
          "persons": [
            {
              "title": "Mr",
              "name": "John Doe",
              "identifier": {
                "scheme": "ID-CARD",
                "id": "123123123"
              },
              "businessFunction": [
                {
                  "type": "authority",
                  "jobTitle": "General Manager",
                  "period": {
                    "startDate": "2018-06-15T00:00:00Z"
                  }
                }
              ]
            }
          ]
        }
      ],
      "buyer": {
        "id": "MD-IDNO-1007601003150",
        "name": "Primaria s. Elizaveta"
      },
      "awards": [
        {
          "id": "ee25c55a-0905-11e9-afab-ab6fe1cdb989",
          "description": "Decizia de atribuire a contractului de achiziții publice nr.1 din 02.01.2019",
          "items": [
            {
              "unit": {
                "name": "Kilogram"
              },
              "quantity": 300,
              "description": "Pulpe de găină congelată fără os",
              "classification": {
                "scheme": "CPV",
                "id": "15800000-6",
                "description": "Diverse produse alimentare"
              },
              "id": "dea5cdbe-fd4c-11e8-bc94-25b0c2da1c29"
            },
            {
              "unit": {
                "name": "Kilogram"
              },
              "quantity": 400,
              "description": "File de pui congelat",
              "classification": {
                "scheme": "CPV",
                "id": "15800000-6",
                "description": "Diverse produse alimentare"
              },
              "id": "dea5cde2-fd4c-11e8-bc94-25b0c2da1c29"
            },
            {
              "unit": {
                "name": "Kilogram"
              },
              "quantity": 600,
              "description": "Pui Broiler",
              "classification": {
                "scheme": "CPV",
                "id": "15800000-6",
                "description": "Diverse produse alimentare"
              },
              "id": "dea5cdcf-fd4c-11e8-bc94-25b0c2da1c29"
            },
            {
              "unit": {
                "name": "Kilogram"
              },
              "quantity": 300,
              "description": "Gambă de curcan fără os",
              "classification": {
                "scheme": "CPV",
                "id": "15800000-6",
                "description": "Diverse produse alimentare"
              },
              "id": "dea5cdd3-fd4c-11e8-bc94-25b0c2da1c29"
            },
            {
              "unit": {
                "name": "Kilogram"
              },
              "quantity": 300,
              "description": "Carne de vită",
              "classification": {
                "scheme": "CPV",
                "id": "15800000-6",
                "description": "Diverse produse alimentare"
              },
              "id": "dea5cdc2-fd4c-11e8-bc94-25b0c2da1c29"
            }
          ],
          "suppliers": [
            {
              "id": "MD-IDNO-1002600003240",
              "name": "Slavena Lux"
            }
          ],
          "value": {
            "currency": "MDL",
            "amount": 104257
          },
          "contractPeriod": {
            "startDate": "2019-01-11T06:17:07.000Z"
          }
        }
      ]
    }
  ]
}

=== open-contracting/standard/docs/examples/organization-personal-identifier.json
{
  "uri": "https://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-02-tender.json",
  "publishedDate": "2010-03-01T09:30:00Z",
  "publisher": {
    "scheme": "GB-COH",
    "uid": "09506232",
    "name": "Open Data Services Co-operative Limited",
    "uri": "https://standard.open-contracting.org/examples/"
  },
  "license": "http://opendatacommons.org/licenses/pddl/1.0/",
  "publicationPolicy": "https://github.com/open-contracting/sample-data/",
  "version": "1.1",
  "extensions": [],
  "releases": [
    {
      "ocid": "ocds-213czf-000-00001",
      "id": "ocds-213czf-000-00001-02-tender",
      "date": "2010-03-15T09:30:00Z",
      "language": "en",
      "tag": [
        "tender"
      ],
      "initiationType": "tender",
      "parties": [
        {
          "id": "COL-IDCARD-1234567",
          "name": "VICTOR HUGO GONZALEZ PEREZ",
          "roles": [
            "tenderer"
          ],
          "identifier": {
            "id": "1234567",
            "scheme": "COL-IDCARD",
            "legalName": "VICTOR HUGO GONZALEZ PEREZ"
          },
          "contactPoint": {
            "name": "VICTOR HUGO GONZALEZ PEREZ"
          }
        }
      ],
      "tender": {
        "id": "ocds-213czf-000-00001-01-tender",
        "title": "Planned cycle lane improvements",
        "description": "Tenders solicited for work to build new cycle lanes in the centre of town.",
        "status": "active",
        "tenderers": [
          {
            "id": "COL-IDCARD-1234567",
            "name": "VICTOR HUGO GONZALEZ PEREZ"
          }
        ],
        "items": [
          {
            "id": "0001",
            "description": "string",
            "classification": {
              "scheme": "CPV",
              "id": "45233130",
              "description": "Construction work for highways",
              "uri": "http://cpv.data.ac.uk/code-45233130"
            },
            "additionalClassifications": [
              {
                "scheme": "CPV",
                "id": "45233162-2",
                "description": "Cycle path construction work",
                "uri": "http://cpv.data.ac.uk/code-45233162.html"
              }
            ],
            "quantity": 8,
            "unit": {
              "name": "Miles",
              "value": {
                "amount": 120000,
                "currency": "GBP"
              }
            }
          }
        ],
        "minValue": {
          "amount": 600000,
          "currency": "GBP"
        },
        "value": {
          "amount": 1100000,
          "currency": "GBP"
        },
        "procurementMethod": "open",
        "procurementMethodRationale": "An open competitive tender is required by EU Rules",
        "awardCriteria": "bestProposal",
        "awardCriteriaDetails": "The best proposal, subject to value for money requirements, will be accepted.",
        "submissionMethodDetails": "Submit through the online portal at http://example.com/submissions/ocds-213czf-000-00001-01/",
        "enquiryPeriod": {
          "startDate": "2010-03-01T09:00:00Z",
          "endDate": "2010-03-14T17:30:00Z"
        },
        "hasEnquiries": false
      }
    }
  ]
}
